### ISSUE TITLE
Two types of cell renderers collide in a tree table

### ISSUE THREAD

**Issue by Sciss** [mgarin/weblaf#106]
I am using a [TreeTable](https://github.com/Sciss/TreeTable) component. That basically nests JTrees inside a JTable. It works fine for most look-and-feels I have tested, but with WebLAF there is this oddity of two types of cell renderers: Table cells use blue background and white foreground, whereas trees (like lists) use a black outline instead. Somehow I end up having white text on light gray background (top to bottom: TreeTable/Tree/Table):

![weblaf](http://i.imgur.com/jiwmO5X.png)

In comparison, Nimbus:

![nimbus](http://i.imgur.com/QCWNFN4.png)

Is there a simple trick to configure a JList or a JTree to use table style cell rendering instead of the outline?

**Comment by stephanebruckert** [comment]
Would you have a quick work-around to disable the gray selection box?

**Comment by mgarin** [comment]
I have added a small change that allows custom tree selection to be switched off.

It can be disabled globally:
```java
WebTreeStyle.selectionStyle = TreeSelectionStyle.none;
```
Or for specific tree or tree UI instance:
```java
final WebTree tree = new WebTree ();
tree.setSelectionStyle ( TreeSelectionStyle.none );
```
```java
final JTree tree = new JTree ();
( ( WebTreeUI ) tree.getUI () ).setSelectionStyle ( TreeSelectionStyle.none );
```

**Comment by mgarin** [comment]
I guess that should also close this question :)
Still, if something is not yet right - feel free to reopen it.

**Comment by stephanebruckert** [comment]
Thanks, that's splendid!

However I could not specifically disable the selection style of my `JXTreeTable` because `JXTreeTable.getUI()` gives a `TableUI` and not a `TreeUI`. The global disabling worked though.

And for the other JTrees in my GUI, the selection style disappeared so I had to enable it again: 

    .setSelectionStyle ( TreeSelectionStyle.line );

**Comment by mgarin** [comment]
You might probably access the tree which `JXTreeTable` uses somehow.
Probably through Reflection - it will still be better than override other trees style every time.

Or you can simply set global selection style to `none` before creating another `JXTreeTable` and then set it back to `line` after you have initialized it. That should initialize `JXTreeTable` with `none` style but will let you avoid customizing other trees.
