### ISSUE TITLE
Possibility to turn off progress bar animation

### ISSUE THREAD

**Issue by Sciss** [mgarin/weblaf#120]
I can't seem to find a way to disable the animation for progress bars. While I don't mind having the animation during actual processing, I have an application where the progress bar remains visible after finishing at 100%. I think the animation should always stop when the bar reaches 100% (this is for example what the Apple LaF does), but also that there should be a way to customise the UI to not use animation at all.

I guess it should be a switch on `WebProgressBarStyle`. I can turn off visible animation via

    WebProgressBarStyle.highlightWhite = new Color(255, 255, 255, 0)
    WebProgressBarStyle.highlightDarkWhite = new Color(255, 255, 255, 0)

Yet that would keep the LaF using CPU power for running an invisible animation, right?

I also tried `StyleConstants.animate = false` but it doesn't seem to have any effect here.

**Comment by mgarin** [comment]
I'll be closing this now as new progress bar implementation will have all settings configurable through the styles including any existing animations.
