### ISSUE TITLE
Frame resize corner disappears on maximize-restore

### ISSUE THREAD

**Issue by MartijnTheunissen** [mgarin/weblaf#132]
This bug is even noticible in the 1.27 demo under the windows decoration tab -> show frame.

When a JFrame is maximized the resize corner stays, and upon minimize it disappears. The window is now unable to be resized. The bug happens on linux and supposedly windows too on JDK 8

Before maximizing
![bug1](https://cloud.githubusercontent.com/assets/5759091/3142185/db4c50e6-e9ae-11e3-91b2-184c76823a87.png)
Maximized:
![bug2](https://cloud.githubusercontent.com/assets/5759091/3142186/ea244696-e9ae-11e3-9262-f0c039fb29af.png)
Unmaximized
![bug3](https://cloud.githubusercontent.com/assets/5759091/3142187/f7e7ce06-e9ae-11e3-91d3-1985a3c7bfe5.png)

Look at the bottom right at the 'drag corner'

**Comment by bspkrs** [comment]
I like the idea of making all borders resizable... I don't think you even need to change the border style for it to be done. If the user gets a resize cursor when hovering over an edge/corner, they will know that the window is resizable.

**Comment by mgarin** [comment]
> I don't think you even need to change the border style for it to be done. If the user gets a resize cursor when hovering over an edge/corner, they will know that the window is resizable.

Exactly. And resizeable corner can be easily made if you really want to have one in your application, but it will never fit in well without customization, so it is kind of pointless to have one forced by the frame or dialog.

**Comment by bspkrs** [comment]
I'm not sure if this is directly related to this defect, but I've noticed in my own application that when using a border layout in the frame content pane if you add a panel or status bar to the southern alignment point the frame resize element is not shown immediately. To get it to show you have to click in just the right place on the corner a few times, then it will be shown over the status bar / whatever. I even tried using Swing.invokeLater() to call setShowResizeCorner(true) after the other elements were added in hopes of preventing it from being painted over, but it didn't work. I probably just need to add a suitable margin to my content pane.
https://gist.github.com/bspkrs/6e72d5ed2e29ec1286f9

**Comment by mgarin** [comment]
Resize corner was a temporary feature I tried to implement to see how it would work and whether it is worth it or not in default decoration setup. As it turned out - it was not worth it due to the the way components are layed out and painted on `JLayeredPane`.

With last commit I have removed `WebResizeCorner` from default root pane setup, but you can easily add it to any container on the frame manually now - in that case it won't hurt application style for sure and will not get overlapped by other components on the frame.

**Comment by mgarin** [comment]
`WebResizeCorner` have been completely removed, instead you can use `WebCanvas` with `StyleId.canvasGripperSE` style (or a style for any other direction) in combination with `ComponentResizeBehavior` or `ComponentMoveBehavior` to resize/move window.
