### ISSUE TITLE
WebFileChooser all files filter disabling doesn't work

### ISSUE THREAD

**Issue by Sorceror** [mgarin/weblaf#142]
I saw the issue https://github.com/mgarin/weblaf/issues/46 and it's probably partially connected.

```Java
FileFilter fileFilter = new AbstractFileFilter() {
    @Override
    public boolean accept(File f) {
        return f.getName().toLowerCase().endsWith(".png");
    }

    @Override
    public ImageIcon getIcon() {
        return null;
    }

    @Override
    public String getDescription() {
        return "PNG File";
    }
};
```

If JFileChooser is chosen than method `setAcceptAllFileFilterUsed()` works as it should.
```Java
WebLookAndFeel.install();

JFileChooser fileChooser = new JFileChooser();
fileChooser.setAcceptAllFileFilterUsed(false);
fileChooser.addChoosableFileFilter(fileFilter);
fileChooser.showDialog(null, "Choose");
```
![JFileChooser version](http://oi58.tinypic.com/ftd8a9.jpg)

But if I directly choose the WebFileChooser component, method `setAcceptAllFileFilterUsed()` does not work at all.
```Java
WebLookAndFeel.install();

WebFileChooser webFileChooser = new WebFileChooser();
webFileChooser.setAcceptAllFileFilterUsed(false);
webFileChooser.addChoosableFileFilter(fileFilter);
webFileChooser.showDialog(null, "Choose");
```
![WebFileChooser version](http://oi58.tinypic.com/sc7u4z.jpg)

**Comment by mgarin** [comment]
I re-checked this issue - it seems that everything works fine so far so I closed this one.
If something is still wrong - feel free to reopen this issue and comment on the case.
