### ISSUE TITLE
Use component name as styleId

### ISSUE THREAD

**Issue by mviktorov** [mgarin/weblaf#148]
Mikle, hello again.

This is just an idea or maybe you will suggest better solution.
I don't want to tie my code to WebPanel, WebLabel, e.t.c. components - just to be able to easily change the LAF if needed.
Using your great XML skinning scheme I can attach default UI styles to standard Swing components: JPanel, JLabel, e.t.c.
But it would be great to be able to set different styles to different panels - the same as you do with Styleable components setting their UI according to "id" XML attribute (\<style type="panel" id="mainPanel"\>).

Idea is the following: Add ability to bind XML styles to components according to their names (component.getName()). As I remember, Synth LAF uses a similar scheme.

I tried the following (I don't know yet if it breaks anything or not).
In WebPanelUI, WebLabelUI, ...:
```java
    @Override
    public void installUI ( final JComponent c )
    {
        ...
        LafUtils.attachStyleIdByNameChangingListener(panel);
    }

    @Override
    public void installUI ( final JComponent c )
    {
        ...
        LafUtils.detachStyleIdByNameChangingListener(panel);
    }
```

In LafUtils:
```java
    private static final PropertyChangeListener SET_STYLE_BY_NAME_PROPERTY_CHANGE_LISTENER = new PropertyChangeListener() {

	@Override
	public void propertyChange(PropertyChangeEvent evt) {
			Object obj = evt.getSource();
			if (obj instanceof Component) {
				ComponentUI ui = getUI((Component) obj);
				if (ui instanceof Styleable)
					((Styleable) ui).setStyleId((String) evt.getNewValue());
			}
		}
	};
    
	/**
	 * Attach listener that changes component's style id according to its name..
	 * This is needed to be able to apply styles to java original swing
	 * components without switching to WebLAF components.
	 * 
	 * @param c
	 */
	public static void attachStyleIdByNameChangingListener(final Component c) {
		c.addPropertyChangeListener("name",
				SET_STYLE_BY_NAME_PROPERTY_CHANGE_LISTENER);
	}
	
	/**
	 * Detach listener that changes component's style id according to its name.
	 * @param c
	 */
	public static void detachStyleIdByNameChangingListener(final Component c) {
		c.removePropertyChangeListener("name", SET_STYLE_BY_NAME_PROPERTY_CHANGE_LISTENER);
	}
```

Best regards,
Mikhail Viktorov

**Comment by mgarin** [comment]
Complete styling support (which is basically a skinning support) will be added with the next update.
As soon as it is released I will post another update here.

**Comment by mgarin** [comment]
There certainly should be a way to set style ID apart from using WebLaF API, but component name is not the best way to do that as it might be already used for different purposes and generally is not designed for that.

I have implemented a different way to set it - simply provide `JComponent` client property with name `styleId` ( `StyleId.STYLE_PROPERTY` ) and it will be used by WebLaF to find appropriate style:
```java
component.putClientProperty ( StyleId.STYLE_PROPERTY, "shaded" );
```
This is equal to the next call:
```java
StyleManager.setStyleId ( component, StyleId.of ( "shaded" ) );
```

You will also be able to provide parent for the style through a client property in the same way you can provide style ID using `parent` ( `StyleId.PARENT_STYLE_PROPERTY` ) property key:
```java
component.putClientProperty ( StyleId.STYLE_PROPERTY, "shaded" );
component.putClientProperty ( StyleId.PARENT_STYLE_PROPERTY, anotherComponent );
```
