### ISSUE TITLE
JProgressBar RTL

### ISSUE THREAD

**Issue by Abu-Abdullah** [mgarin/weblaf#154]
Hi,

JProgressBar animation is not rendered correctly in RTL. it is started from LTR in all cases

**Comment by mgarin** [comment]
Progress bar have been updated and now fully supports new styling system in the latest `styling` branch builds. Those are available on the site and in maven:
http://weblookandfeel.com/downloads/styling/
https://oss.sonatype.org/content/repositories/snapshots/com/weblookandfeel/
