### ISSUE TITLE
File Chooser: make table sortable

### ISSUE THREAD

**Issue by Sciss** [mgarin/weblaf#161]
It would be great if in the details-view one could have the view sorted by any column, e.g. alphabetically by name, or by creation date, or by file size.

**Comment by Sciss** [comment]
Ok great. Although I think you don't need to implement anything specific in the table UI — row sorters are a standard Swing features, and AFAIK I'm using some sorted tables already somewhere with WebLaF and no issues. So this would only mean to enable the row sorter and perhaps customise the comparators a bit.

**Comment by mgarin** [comment]
Actually that depends on "how far" will I go with sorting implementation.
Cannot say for sure yet, will see.

**Comment by mgarin** [comment]
Closing this according to changes in #259 
Table sorting improvements will be available with later updates.
