### ISSUE TITLE
File Chooser: thread pool not shutdown

### ISSUE THREAD

**Issue by ayinger1** [mgarin/weblaf#172]
there is a lingering non-Daemon thread after using File Chooser with this look and feel.

after i shutdown my app, i can see this thread still running:
   pool-2-thread-1 class: Thread isDaemon: false

i only see this thread if i use WebLookAndFeel *and* start a file open dialog.  so i'm guessing that the implementation of this dialog starts a thread pool.  this thread pool should be shutdown when the dialog is closed, right?

**Comment by ayinger1** [comment]
when will this fix (in v1.29) be released to Maven Central?

**Comment by mgarin** [comment]
I'm not releasing WebLaF artifacts into Maven yet - the ones you are probably using are released by @Sciss - he might update artifacts with v1.29 as soon as it is released, but it is not yet.

I might be able to publish artifacts into Maven after v1.29 release.
But I'm still working on the changes, so it isn't going to be there for quite some time.

You can keep the track of updates related to Maven here: https://github.com/mgarin/weblaf/issues/89

**Comment by Sciss** [comment]
Perhaps it makes sense to publish more regular minor versions before this huge 1.29 milestone? If the current state in master is more or less stable, I could publish it. The only question then is about the version number scheme to use.

**Comment by ayinger1** [comment]
yes, that would be nice -- been waiting awhile for this bugfix to get into an official release.

**Comment by mgarin** [comment]
It does, but as already said a few times before - it is only v1.29 that took quite a huge timeframe. Futher updates will be released much more frequently.
