### ISSUE TITLE
Build fails due to WebLabel

### ISSUE THREAD

**Issue by ExPixel** [mgarin/weblaf#175]
I've had problems building the library because of issues with the WebLabel. The errors I get come from the ambiguity in these two method signatures: `WebLabel(String, int, Object)` and `WebLabel(String, Object...)`. Is there something I'm missing?

**Comment by mgarin** [comment]
It seems that this issue also appears on some versions of JDK 8 so I will keep the changes made.
Anyway, closing this issue.
