### ISSUE TITLE
TabbedPane rendering bug

### ISSUE THREAD

**Issue by Sorceror** [mgarin/weblaf#181]
I like the possibilities and styling of `WebTabbedPane` and we use it in our project a lot, but this one thing drives me crazy and I spend few hours to track down what might cause the problem. Finally, there seems to be **off-by-one bug in `WebTabbedPane` tab handle rendering**.

![tabbug](https://cloud.githubusercontent.com/assets/944282/4346521/b3cfc4f6-4103-11e4-9742-545f7361dd65.png)

Because my layout manager (MigLayout) does not give any additional space (inset/indentation) to the component, bottom line of selected component is not visible.

![tabbug2](https://cloud.githubusercontent.com/assets/944282/4346526/e07ead00-4103-11e4-8d7d-6bbb400ef34d.png)

**Comment by mgarin** [comment]
Closing this issue and merging all information into #35
Tabbed pane will be getting a major update quite soon
