### ISSUE TITLE
Display week number in calendar

### ISSUE THREAD

**Issue by oliviermorpa** [mgarin/weblaf#189]
Hi again,
is there a possibility to show the week number in the calendar ?

**Comment by oliviermorpa** [comment]
good pm,

one year now that i ask this :-)
 It's very important for us because we use week number every day.

Can i help you to do that ? it's very important for us and after one year, customers gets a little angry to me :-)

have a nice day
Olivier

**Comment by mgarin** [comment]
Sorry for the delay with this enhancement, I wanted to release update long ago, but had to delay it due to all the changes coming.

I will add this enhancement in the upcoming v1.29 instead of later one, but I am still working on it and that will take some time. There will be a new preview version available soon with all the changes made - it will give you a quick preview on changes coming with the final release. It will be incomplete so I do not recommend using it in production yet.

I will post a separate update here when this specific enhancement is available within preview and final release as well.

**Comment by mgarin** [comment]
Just to make sure - you want to be able to see week number inside the calendar popup, right?

**Comment by oliviermorpa** [comment]
thanks for your fast reply.

we want only display week number: to add week number in first column:

exemple, today we have
    1   2    3   4   5   6   
7   8   9  10  11 12 13
14 15 16 17 18 19 20
21 22 23 24 25 26 27
28 29 30

and we would

32    1   2    3   4   5   6   
33 7   8   9  10  11 12 13
34 14 15 16 17 18 19 20
35 21 22 23 24 25 26 27
36 28 29 30
 
thanks and have a nice day

**Comment by mgarin** [comment]
Thanks for the clarification! 
I will include this enhancement in v1.29.

**Comment by oliviermorpa** [comment]
thanks so much.
do you know approximatly when will done the 1.29 release ?

**Comment by mgarin** [comment]
I will be posting a lot of information next week on the site.
It will include the current state of the project and ETA on the v1.29 update.
Right now I am working on getting all pieces together for that update post :)

**Comment by oliviermorpa** [comment]
good pm,
any news ? can you tell me approximately when u can include the week number ?
my costumers ask me again and again...

**Comment by mgarin** [comment]
Sorry for the delay, I really had to finish the update on the current state. By the way you can read here: http://weblookandfeel.com/2015/11/20/update-on-styling-branch-changes/
ETA on v1.29 is also revealed there.

Regarding the week number - it will certainly be included in the release, but I am not sure whether or not I will be able to include it into current pre-release version based on current master branch. I will be able to tell for sure when I get to its implementation on the styling branch on the next week. I will add an update here as soon as get to it.

**Comment by oliviermorpa** [comment]
good pm and happy new year :-)

i come back to know if you have a date of release ?
i'm sorry to ask again but it becomes very critical with customers. it's already one year than they are waiting.
If you don't have time, can i help you ?

**Comment by mgarin** [comment]
As mentioned in the large news post on the site I linked above - v1.29 update will be released on January 25th - final builds and source will be available on the site and here on GitHub. There will also be new guides added to GitHub wiki for new components and features that are still not mentioned.

A lot of changes will also be released before that date, but they will only be added into the intermediate WebLaF version that can be found in `styling` branch right now. At this point I want to avoid adding any more changes into older version and just push the release as I still have a lot of things to fix until the release date.

And sorry for the delay with the answer - right now I am away from the office for the holidays and having issues accessing our mail servers. This will be fixed soon and I will get all the emails I missed out, but for now I am cut from it and therefore from any notifications.

**Comment by oliviermorpa** [comment]
good pm,
thanks for your reply.
i understand that you dont want to add new features.

Can you please give an estimated date of release please for this feature ?

sorry to ask again but we change our old component with your component and i didn't see that this feature (display week number) was not enable in your component.
it's like a "rollback" for our customers and they dont understand why we have change our component ...
and it's more than 1 year i say it will come ...

I'm under fire now :-/
thanks and have a nice day

**Comment by mgarin** [comment]
As I said before -

> I will include this enhancement in v1.29.

so it will be there with the release of v1.29 on January 25.

**Comment by oliviermorpa** [comment]
thank you so much.
i'm a little slow. i don't understand always ;-)

**Comment by oliviermorpa** [comment]
good morning,

sorry to ask again, but i didn't see anything about week calendar on january 25.
Do you have any news about that?
Thank and have a nice day

**Comment by mgarin** [comment]
Yes, unfortunately I had to delay the release and I am working hard to push it live. 

Concerning this specific change - I have pushed it into the `styling` branch a few moments ago, so it will certainly be available in final release. Here is a preview of calendar with weeks display enabled:
![image](https://cloud.githubusercontent.com/assets/2361389/13142653/8dc4ab9a-d64f-11e5-9afa-8bc10805c36d.png)

What you need to do to switch it on is:
```java
final WebCalendar calendar = new WebCalendar ();
calendar.setDisplayWeekNumbers ( true );
```
for `WebCalendar` component or:
```java
final WebDateField dateField = new WebDateField ();
dateField.setCalendarCustomizer ( new Customizer<WebCalendar> ()
{
    @Override
    public void customize ( final WebCalendar calendar )
    {
        calendar.setDisplayWeekNumbers ( true );
    }
} );
```
for `WebDateField` component.

**Comment by Endogen** [comment]
I could imagine that this is a bit to much, but anyway: In germany we call the calendar week "KW" from "Kalenderwoche". Everyone will recognize it that way. Is it possible to set the String "KW" instead of "#"?

**Comment by oliviermorpa** [comment]
good pm,
thanks a lot. waiting the release ;-)

in French, we don't know what KW is :-) so keep it #

**Comment by Endogen** [comment]
I didn't mean to change "#" to "KW". I meant it would be usefull to have the option to set the String yourself

**Comment by mgarin** [comment]
Week number column title is added into `language.xml` and can be replaced if you want to:
```xml
<Dictionary prefix="weblaf">
    ...
    <Dictionary prefix="ex">
        ...
        <Dictionary prefix="calendar">
            <record key="weekNumber">
                <value lang="en">#</value>
                <value lang="ru">#</value>
                <value lang="pl">#</value>
                <value lang="ar">#</value>
                <value lang="es">#</value>
                <value lang="fr">#</value>
                <value lang="pt">#</value>
                <value lang="de">#</value>
                <value lang="it">#</value>
                <value lang="tr">#</value>
            </record>
            ...
        </Dictionary>
        ...
    </Dictionary>
    ...
</Dictionary>
```

**Comment by mgarin** [comment]
I guess if you are saying that "KW" is a common thing - I will just put it as default for `de` translation.

**Comment by Endogen** [comment]
Great! Thanks

**Comment by oliviermorpa** [comment]
good am,
one month after, when will you upload the new release to get this new feature ?
Thanks and have a nice day

**Comment by mgarin** [comment]
@oliviermorpa Unfortunately I am still working on a few remaining problematic components and some general styling system enhancements which are necessary for the final release.

Meanwhile you might want to try out the pre-release build of the next WebLaF version on your project - a lot of major changes and API breaks happened there which might affect some parts of your code. You can create `styling` version build using source code and ANT build from the branch: https://github.com/mgarin/weblaf/tree/styling

Also you might want to join online project chat on Gitter: https://gitter.im/mgarin/weblaf
It is one the fastest way to contact me and quickly discuss any matter related to WebLaF.
Mostly some styling-related discussions are held there right now.
