### ISSUE TITLE
maximize if using 2 screens

### ISSUE THREAD

**Issue by oliviermorpa** [mgarin/weblaf#195]
hi,
if we use two monitor, then when we maximize the web frame (button maximize from the webframe) is giving a small size of the windows. i think it calculate the maximum size window FROM the first monitor (who is smaller definition than the second)  EVEN we maximize from the second monitor.

**Comment by oliviermorpa** [comment]
good pm,
thus bug is important for us.
Can you please fix it ?
Thanks

**Comment by mgarin** [comment]
I have added a small fix that could possibly solve this specific issue.
Unfortunately I can't confirm that right now.

You can try out the latest build from here:
http://weblookandfeel.com/downloads/prerelease/
and see if it helps or not.

**Comment by oliviermorpa** [comment]
its ok with this patch
thanks

**Comment by mgarin** [comment]
Glad that helped!

I will keep issue open for the final re-check before the release.
This is a one-time measure just for the v1.29, so nevermind it :)

**Comment by oliviermorpa** [comment]
there is a strange behavior if using 2 screens on windows:
if you change to the second windows then first window the second again, maximize the window, sometimes it's disappear in task bar and impossible to get it back to the screen.
need to do right click on java task bar and show all windows. then he appear again.

**Comment by oliviermorpa** [comment]
it's more easy to reproduce the problem. if you go to the second screens, then maximize the frame, it disappear !!! in the task bar and impossible to restaure it .

**Comment by mgarin** [comment]
Could you provide exact steps to reproduce this one?..
Since I am not sure I understood the issue by the description you have provided.

Steps like:
1. Attach second screen under Windows
2. Open application with JFrame decorated by WebLaF (not native Windows decoration)
3. ...
etc.

**Comment by oliviermorpa** [comment]
sorry for my poor english ;-)

on windows with java 1.8:
1. screen on window 1: maximize: OK
2. make again regular size (click maximize)
3. move to second windows
4. maximize: it's like i click reduce to taskbar and impossible to get it back on window

**Comment by mgarin** [comment]
I were able to find and fix this issue.
It should now work properly on any size and any amount of additional screens under Windows.
Not sure that the same bounds would work properly under Linux/Mac systems - will check that soon.

So far this fix is available only in the sources here, but I will be releasing updated pre-release artifacts tomorrow after some other changes.

**Comment by mgarin** [comment]
Updated pre-release artifacts are now available here:
http://weblookandfeel.com/downloads/prerelease/
