### ISSUE TITLE
Notification balloons always appear on primary monitor instead of active monitor with 1.29 preview

### ISSUE THREAD

**Issue by chaddaniels** [mgarin/weblaf#197]
When I am using the demo app on a secondary monitor, notification balloons still appear on the primary monitor.  This could lead to missed notifications for the user.

**Comment by mgarin** [comment]
I have added an improvement that allows notifications to be displayed on secondary screens. This change is available only is source form so far, but I will be releasing updated pre-release artifacts soon.

**Comment by mgarin** [comment]
Updated pre-release artifacts are now available here:
http://weblookandfeel.com/downloads/prerelease/
