### ISSUE TITLE
WebInnerNotifications don't work properly on secondary displays in 1.29 preview

### ISSUE THREAD

**Issue by chaddaniels** [mgarin/weblaf#198]
Using OSX 10.10 with JDK 1.8.0_11 and weblaf 1.29 preview.

I attempted to use WebInnerNotification on a secondary display and got very weird results.  This is what I did:

1.) Display a WebInnerPopup while application is on a secondary display
2.) The popup does not show at all on any display
3.) Start to move the application window around on the secondary screen
4.) The notification popup becomes visible in the bottom right corner of the primary display, and moves in coordination with the application window that is still in the secondary display

There is another weird side effect where the notification balloon sits within another notification balloon, but I think this is happening on all WebInnerNotification balloons, and not just when the application is on a secondary monitor.  I will be creating another issue for this behavior.

**Comment by mgarin** [comment]
I have re-checked this to be sure - it seems to work just fine :)
So I will actually close this one. If something weird is still happening - feel free to reopen this issue.

There is a small enhancement that could be made though - non-inner notifications can only be displayed on the main screen so far - I will be changing that in the next update: #239
