### ISSUE TITLE
WebDocumentPane setDragBetweenPanesEnabled not honored

### ISSUE THREAD

**Issue by chaddaniels** [mgarin/weblaf#200]
In 1.29 preview the setDragBetweenPanesEnabled in WebDocumentPane is not honored.  I tried setting the value to false and was still able to drag the panels to whichever tabbed pane I wanted.  Tested on Mac and Windows in multiple JDK versions with the same results.

**Comment by mgarin** [comment]
Changes to the behavior were added in 073d82d commit.
This setting will now have proper effect when it is changed.

**Comment by mgarin** [comment]
Also I have tried running a few tests on the latest version from `styling` branch and were unable to reproduce the native exception you have posted earlier. It is either "cured" or there is something special I am missing.

**Comment by mgarin** [comment]
Will mark this issue solved for now, but if it still persists in newer versions of WebLaF I will have a closer look at it once more.

**Comment by mgarin** [comment]
I am still unable to reproduce this issue - feel free to reopen if it still appears for you on v1.29 `styling` snapshot version (or release version later on).
