### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by oliviermorpa** [mgarin/weblaf#220]
we are using differents windows in our application and when we have a webpopover in one window and click on other window, then java generate error and we have to kill the appli.
its happen ONLY IF WEBPOPOVER IS PUT TO MODAL.
last java and mac and last prerelease.

final WebPopOver popOver = new WebPopOver(jCompo);
popOver.setModal(true);
popOver.show(jCompo, PopOverDirection.down);

crash:
2015-01-29 15:50:57.519 java[1371:53700] *** Assertion failure in -[AWTWindow_Normal _changeJustMain], /SourceCache/AppKit/AppKit-1343.16/AppKit.subproj/NSWindow.m:13944
2015-01-29 15:50:57.519 java[1371:53700] Invalid parameter not satisfying: [self canBecomeMainWindow]
2015-01-29 15:50:57.521 java[1371:53700] (
	0   CoreFoundation                      0x00007fff93b0964c __exceptionPreprocess + 172
	1   libobjc.A.dylib                     0x00007fff926f16de objc_exception_throw + 43
	2   CoreFoundation                      0x00007fff93b0942a +[NSException raise:format:arguments:] + 106
	3   Foundation                          0x00007fff996785b9 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 195
	4   AppKit                              0x00007fff8f26a371 -[NSWindow _changeJustMain] + 295
	5   Foundation                          0x00007fff995eaf4c __NSThreadPerformPerform + 293
	6   CoreFoundation                      0x00007fff93a27661 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	7   CoreFoundation                      0x00007fff93a197ed __CFRunLoopDoSources0 + 269
	8   CoreFoundation                      0x00007fff93a18e1f __CFRunLoopRun + 927
	9   CoreFoundation                      0x00007fff93a18838 CFRunLoopRunSpecific + 296
	10  HIToolbox                           0x00007fff8d76e43f RunCurrentEventLoopInMode + 235
	11  HIToolbox                           0x00007fff8d76e0be ReceiveNextEventCommon + 179
	12  HIToolbox                           0x00007fff8d76dffb _BlockUntilNextEventMatchingListInModeWithFilter + 71
	13  AppKit                              0x00007fff8f1106d1 _DPSNextEvent + 964
	14  AppKit                              0x00007fff8f10fe80 -[NSApplication nextEventMatchingMask:untilDate:inMode:dequeue:] + 194
	15  libosxapp.dylib                     0x00000001134446f4 -[NSApplicationAWT nextEventMatchingMask:untilDate:inMode:dequeue:] + 124
	16  AppKit                              0x00007fff8f103e23 -[NSApplication run] + 594
	17  libosxapp.dylib                     0x0000000113444557 +[NSApplicationAWT runAWTLoopWithApp:] + 156
	18  liblwawt.dylib                      0x000000011339cba9 -[AWTStarter starter:] + 873
	19  Foundation                          0x00007fff995eaf4c __NSThreadPerformPerform + 293
	20  CoreFoundation                      0x00007fff93a27661 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	21  CoreFoundation                      0x00007fff93a197ed __CFRunLoopDoSources0 + 269
	22  CoreFoundation                      0x00007fff93a18e1f __CFRunLoopRun + 927
	23  CoreFoundation                      0x00007fff93a18838 CFRunLoopRunSpecific + 296
	24  java                                0x00000001067613b0 CreateExecutionEnvironment + 871
	25  java                                0x000000010675bb5c JLI_Launch + 1952
	26  java                                0x000000010676170d main + 101
	27  java                                0x000000010675b3b4 start + 52
	28  ???                                 0x0000000000000007 0x0 + 7
)

**Comment by mgarin** [comment]
That is a pretty weird one... Here are a few questions I have:
- It didn't happen with the previous version or you just didn't try modal pop-over before?

- Could you try simple JDialog with modal flag instead - will this issue appear as well?

- If it doesn't appear with simple JDialog - try making it undecorated, will that change anything?

- What are other windows in your application exactly? Instances of JFrame?

**Comment by mgarin** [comment]
I've searched for similar issues and found a few, solution there shortly was to use `requestFocus()` instead of `requestFocusInWindow()` in the application. This might be a case with WebLaF as well, I'll be replacing `requestFocus()` calls to see if it helps.

**Comment by mgarin** [comment]
This issue seems to be solved now.
You might still want to try it out on the `styling` branch version.
