### ISSUE TITLE
issue with JFileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);

### ISSUE THREAD

**Issue by Abu-Abdullah** [mgarin/weblaf#225]
Hi,

It seems the following is not working in webLaF: JFileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);

**Comment by Abu-Abdullah** [comment]
sorry, i just tried it with the prerelease 1.29 and it seems it is resolved

**Comment by mgarin** [comment]
Yep, this issue was solved some time ago and fix will be in the final v1.29 :)
