### ISSUE TITLE
WebLookAndFeel.setDecorateDialogs resizing and setRound Panel

### ISSUE THREAD

**Issue by oliviermorpa** [mgarin/weblaf#228]
the Frame cannot be resize from the border (only at the corner under left)
and the Panel is outside the frame (corner under left). so it's difficult to resize.

Possible to adpat corner in Panel ?
Possible to resize by clicling on the border on the frame ?

	com.alee.laf.WebLookAndFeel.install();
		com.alee.laf.WebLookAndFeel.setDecorateFrames(true);
		WebLookAndFeel.setDecorateDialogs(true);
		WebFrame f = new WebFrame("");
		f.setDefaultCloseOperation(WebFrame.DISPOSE_ON_CLOSE);
		
		f.setRound( 25);
		f.setAttachButtons(true);
		f.setShadeWidth(0);
		WindowListener l = new WindowAdapter() {

			public void windowClosing(WindowEvent e) {

				System.exit(0);

			}

		};
		f.addWindowListener(l);
		JLabel e = new JLabel("add");
		

		com.alee.laf.panel.WebPanel p1 = new com.alee.laf.panel.WebPanel();
		p1.setRound(25);
		p1.setLayout(new BorderLayout());
		p1.add(e,BorderLayout.CENTER);
		f.setLayout(new BorderLayout());
		f.add(p1,BorderLayout.CENTER);
		
		f.setLocation(200, 200);
		f.setSize(200, 400);
		f.setVisible(true);

**Comment by oliviermorpa** [comment]
it's setDecorateFrames and not setDecorateDialogs

**Comment by mgarin** [comment]
Frame resize using frame border drag will be included in v1.30 update. It had some issues so I decided to postpone these changes until required modifications are made within the code.

**Comment by oliviermorpa** [comment]
it's very painfull this behavior.
some customers change the windows size to big then the windows are outside the windows screen. and if the corner under right is outside and the windows too big, then it's impossible to resize to the right size because the corner under right is ALWAYS outside the window frame.

if the customer could resize on other corner, it will be ok, but for now, they need to quiet the software if it's happen (no choice).

**Comment by mgarin** [comment]
Since `ComponentResizeBehavior` is now properly implemented - I have added its usage for decorated frames and dialogs. Those should now be easily resizable by dragging either of the window sides.
