### ISSUE TITLE
Feature: allow table sorting in details-view of JFileChooser

### ISSUE THREAD

**Issue by Sciss** [mgarin/weblaf#230]
It would be fantastic if the table used in the "Details" view of the file-chooser would allow sorting, so that one can switch between alphabetical (default), sorted-by-type, sorted-by-size, and sorted-by-modification-date.

**Comment by mgarin** [comment]
I will be implementing table sorting in v1.30 update, so this enhancement will also be possible there.
Main table sorting enhancement issue: #164
