### ISSUE TITLE
webTextField not enable with java 1.8.40

### ISSUE THREAD

**Issue by oliviermorpa** [mgarin/weblaf#236]
it's a urge critical problem.
since the update to java 1.8.40, webtextfield is ALWAYS not editable when using with javawebstart.
with java (lauching with eclipse), it's ok but not when launching with javawebstart.

public class Test {

	public static void main(String argv[]) {
	/*	com.alee.laf.WebLookAndFeel.install();
		com.alee.laf.WebLookAndFeel.setDecorateFrames(true);
		WebLookAndFeel.setDecorateDialogs(true);
		WebFrame f = new WebFrame("");
		f.setRound( 25);
		f.setAttachButtons(true);
		f.setShadeWidth(0);
	
		*/JFrame f = new JFrame();
		f.setDefaultCloseOperation(WebFrame.DISPOSE_ON_CLOSE);
		
		WindowListener l = new WindowAdapter() {

			public void windowClosing(WindowEvent e) {

				System.exit(0);

			}

		};
		f.addWindowListener(l);
		com.alee.laf.text.WebTextField e = new com.alee.laf.text.WebTextField("Text with Weblaf");
		

		com.alee.laf.panel.WebPanel p1 = new com.alee.laf.panel.WebPanel();
		p1.setRound(25);
		p1.setLayout(new BorderLayout());
		p1.add(e,BorderLayout.CENTER);
		f.setLayout(new BorderLayout());
		f.add(p1,BorderLayout.CENTER);
		
		f.setLocation(200, 200);
		f.setSize(200, 400);
		f.setVisible(true);

	

	}

}

**Comment by oliviermorpa** [comment]
forget to say: only with MAC os.
it's still ok with windows

**Comment by oliviermorpa** [comment]
the probleme disappear when i dont do
f.setDefaultCloseOperation(WebFrame.DISPOSE_ON_CLOSE);

it's this function the problem

**Comment by oliviermorpa** [comment]
i close it because it's a java bug.
Bug appears with macos java 1.8.40 and when the code is :+1: f.addWindowListener(new WindowAdapter() {
			public void windowClosing(WindowEvent e) {

			System.exit(0);
			}
		});

then all jtextfields are not enable !!!

**Comment by mgarin** [comment]
It seems they have "introduced" a bunch of new issues with u40.
Hopefully those will be fixed in next updates.
