### ISSUE TITLE
Font rendering issues on non-opaque windows

### ISSUE THREAD

**Issue by oliviermorpa** [mgarin/weblaf#237]
good pm,
when using weblaf, the font is not the same than with nimbus.
I try manny things , but i can't fix it.
It seems to be sansserif in nimbus and i put the same in weblaf but still have a difference
see attach file
when using weblaf, it's a little thiny

have a nice day
![font](https://cloud.githubusercontent.com/assets/9378538/6637037/90f8d25c-c9b0-11e4-8ec7-f2f238c7cd2d.png)

**Comment by mgarin** [comment]
Are you using decorated frames/dialogs to display content where this difference appears?

**Comment by oliviermorpa** [comment]
yes but it seems to be same of i dont use it
	com.alee.laf.WebLookAndFeel.setDecorateFrames(true);
		WebLookAndFeel.setDecorateDialogs(true);

the difference is when im using nimbus (not weblaf) and when i use your weblaf (put same font sans serif). it's like you dont have anti aliasing, possible ?

**Comment by mgarin** [comment]
So my guess was right. The point is - on undecorated non-opaque windows (like the custom-decorated ones in WebLaF) all font aliasing made by some Java rendering engine and not with the native one. So unfortunately in most cases you will see the difference in the font.

This is a pretty old issue in JDK and actually I don't think it will ever be fixed.
There were also a few other issues in this tracker added for the same reason, like this one: #130

**Comment by mgarin** [comment]
If something changes - for example a fix is actually released in some newer JDK version - I will certainly make a note here.

**Comment by mgarin** [comment]
For now I will be closing all issues which are in `wontfix` or `solved` state.
Again - if something changes about this issue on newer JDKs I will provide additional information here.

**Comment by mgarin** [comment]
I'll keep this issue opened to reference in case something changes regarding the subpixel rendering on non-opaque windows.

**Comment by mgarin** [comment]
All discussions regarding this issue will be held in #130, you can follow it to track updates.
