### ISSUE TITLE
Build error in WebComboboxUI

### ISSUE THREAD

**Issue by iMichka** [mgarin/weblaf#250]
Since the change here:
https://github.com/mgarin/weblaf/commit/0b7debf9d446cb30fca9d1189a11ef74b81f94d1#diff-1410adf8ca03d1412bad771b7d8342a7R985

I get the following build error:
```
WebComboBoxUI.java:985: method does not override or implement a method from a supertype
    [javac]     @Override
```

**Comment by mgarin** [comment]
This is pretty weird - the only possible case is that this method doesn't exist anymore on the JDK version you are using to compile WebLaF. What is your JDK version?

**Comment by mgarin** [comment]
Yep, I was right, this method was made `protected` instead of `private` either in JDK 7 or 8.
I have removed the annotation for good.

**Comment by iMichka** [comment]
I use Java 6, though we plan to upgrade soon. Thanks for the fix.

**Comment by mgarin** [comment]
Yep, that line got accidentally auto-refactored when I switched to JDK 8 to test out some stuff.
And I didn't notice the issue until I switched back to JDK 6 u30.
