### ISSUE TITLE
Radiobutton isSelected with model

### ISSUE THREAD

**Issue by iMichka** [mgarin/weblaf#256]
Hi

while implementing Weblaf in our software, I found out that all theRadioButtons are deselected at start.

![radio](https://cloud.githubusercontent.com/assets/3406519/6800399/5e0710d6-d21e-11e4-89fe-9379f4df1fa8.jpg)

We use a model to set the state of the radiobuttons. I put a small example below. Commenting out the line "WebLookAndFeel.install();" shows a radiobutton which is checked, with WebLaf the Radiobutton is unchecked. Could you have a look into this ?

Thanks

```
import java.awt.Container;
import java.awt.EventQueue;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.GroupLayout;
import javax.swing.JRadioButton;
import javax.swing.JComponent;
import javax.swing.JFrame;
import javax.swing.JToggleButton;

import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;

import com.alee.laf.WebLookAndFeel;

public class Radio extends JFrame {

    public Radio() {
        initUI();
    }

    private void initUI() {

        WebLookAndFeel.install();

        final JRadioButton radioButton = new JRadioButton("Radio button");

        JToggleButton.ToggleButtonModel model = new MyModel();
        radioButton.setModel(model);

        createLayout(radioButton);

        setTitle("Radio Button");
        setSize(300, 200);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
    }

    protected static final class MyModel
            extends JToggleButton.ToggleButtonModel
            implements PropertyChangeListener {

        protected MyModel() {}

        @Override
        public boolean isSelected() {
            System.out.println("isSelected");
            return true;
        }

        @Override
        public void setSelected(boolean b) {
            System.out.println("setSelected");
        }

        @Override
        public void propertyChange(PropertyChangeEvent e) {
            System.out.println("propertyChange");
        }
    }

    private void createLayout(JComponent... arg) {

        Container pane = getContentPane();
        GroupLayout gl = new GroupLayout(pane);
        pane.setLayout(gl);

        gl.setAutoCreateContainerGaps(true);

        gl.setHorizontalGroup(gl.createSequentialGroup()
                .addComponent(arg[0])
        );

        gl.setVerticalGroup(gl.createSequentialGroup()
                .addComponent(arg[0])
        );
    }

    public static void main(String[] args) {

        EventQueue.invokeLater(new Runnable() {
        
            @Override
            public void run() {
                Radio ex = new Radio();
                ex.setVisible(true);
            }
        });
    }
}
```

**Comment by mgarin** [comment]
This is indeed looks like an issue, thanks for reporting!
I will investigate what can cause that.

**Comment by mgarin** [comment]
I have committed a small fix for this issue, radio button will now properly update on model changes.
Can you check whether this fix helps? Or you will be waiting till next available artifacts build?

**Comment by iMichka** [comment]
I just rebuilt the jar, it works perfectly. Thanks very much for the quick fix !

**Comment by iMichka** [comment]
Hi. I have still some trouble with Radiobuttons. The problem described above is fixed, but I got another one.

If in my model I have a field to store the state (selected/deselected), I can make the radiobutton switch to on/off while clicking on it with normal swing. With WebLaf this does not work.
I reduced the example, which is slightly the same. The only difference is that I added the ```selected``` field. The field is correctly updated when clicking on the radiobutton, but no repaint is triggered in WebLaf. Comment/Uncomment  ```WebLookAndFeel.install();``` to see the difference.

```
import java.awt.*;
import javax.swing.GroupLayout;
import javax.swing.JRadioButton;
import javax.swing.JComponent;
import javax.swing.JFrame;
import javax.swing.JToggleButton;

import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;

import com.alee.laf.WebLookAndFeel;

public class Radio extends JFrame {

    public Radio() {
        initUI();
    }

    private void initUI() {

        WebLookAndFeel.install();

        final JRadioButton radioButton = new JRadioButton("Radio button");

        JToggleButton.ToggleButtonModel model = new MyModel();
        radioButton.setModel(model);

        Container pane = getContentPane();
        pane.setLayout(new FlowLayout());
        pane.add(radioButton);

        setTitle("Radio Button");
        setSize(300, 200);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
    }

    protected static final class MyModel
            extends JToggleButton.ToggleButtonModel
            implements PropertyChangeListener {

        private boolean selected = false;

        protected MyModel() {}

        @Override
        public boolean isSelected() {
            System.out.println("isSelected " + selected);
            return selected;
        }

        @Override
        public void setSelected(boolean b) {
            System.out.println("setSelected " + b);
            this.selected = b;
        }

        @Override
        public void propertyChange(PropertyChangeEvent e) {
            System.out.println("propertyChange");
        }
    }

    public static void main(String[] args) {

        EventQueue.invokeLater(new Runnable() {
        
            @Override
            public void run() {
                Radio ex = new Radio();
                ex.setVisible(true);
            }
        });
    }
}
```

**Comment by mgarin** [comment]
I have checked this one and I'm not really sure how I can help there. Indeed `WebRadioButtonUI` is different from the default implementation - it starts displaying selection only when it have received `itemStateChanged` from the radio button. The basic radio button implementation simply always paints the current state of the selection, requesting it directly from the model.

The problem is - your implementation of the model does not inform underlying listeners about state change and therefore WebRadioButtonUI doesn't react to the changes made. To be honest, in terms of Swing such implementation is wrong because it doesn't inform UI about model changes, which basically leads to "outdated" UI. If you look at any model implementation in Swing you will find that each of those models fire appropriate events when something changes which allows UI to update properly, according to the changes made.

You can easily fix this problem by adding appropriate `fire` call into your model:
```java
    protected static final class MyModel extends JToggleButton.ToggleButtonModel implements PropertyChangeListener
    {
        private boolean selected = false;

        protected MyModel ()
        {
        }

        @Override
        public boolean isSelected ()
        {
            System.out.println ( "isSelected " + selected );
            return selected;
        }

        @Override
        public void setSelected ( final boolean b )
        {
            System.out.println ( "setSelected " + b );
            this.selected = b;

            // Send ItemEvent
            fireItemStateChanged ( new ItemEvent ( this, ItemEvent.ITEM_STATE_CHANGED, this,
                    this.isSelected () ? ItemEvent.SELECTED : ItemEvent.DESELECTED ) );
        }

        @Override
        public void propertyChange ( final PropertyChangeEvent e )
        {
            System.out.println ( "propertyChange" );
        }
    }
```
It also exists in original `JToggleButton.ToggleButtonModel` class.

**Comment by iMichka** [comment]
Hi. Thanks for the detailed answer.

In fact in most of our code, we already use our own model which triggers the fireItemStateChanged. I just stumbled on some radiobuttons which used another mechanism to update the UI, but this was no more working with WebLaf. Navigating through legacy code can sometimes be tedious. Triggering the event fixes it. Thanks for the help.

**Comment by mgarin** [comment]
No problem, glad that solution works for you :) 

I actually had a hard time deciding whether this should or shouldn't be checked internally. In the end I decided that it is better not to add any workarounds for situations which normally should not appear. At least to avoid other possible issues with those workarounds in future and keep the code as clean as it could be.
