### ISSUE TITLE
webdatefield with wrong day

### ISSUE THREAD

**Issue by oliviermorpa** [mgarin/weblaf#257]
Hi,
it's very strange. when 
- i open a windows and have a webdatefield (exemple set on march 13 2015).
- i open the popup to select a day
- i change month through the right arrow (i see april 2015 with no select)
- i dont click but go outside webdatefield
- i setvisible(false) to the frame
- i setvisible(true)
- i put my webdatefield on march 13 2015 again (setDate)
- i open the popup calendar: I SEE APRIL month BUT with the title MARCH !!!!
- i select 15 and he write april 15 2015 (what is true)

the probleme is that your month title show the month from the value of webdatefield and the month is what i had seen last time (april)

i hope you understand. see the screenshot : it's MARCH but the day is APRIL ...
![capture d ecran 2015-03-24 a 23 07 39](https://cloud.githubusercontent.com/assets/9378538/6805183/9fcd8b9a-d27c-11e4-9125-7b337c6be75a.png)

**Comment by oliviermorpa** [comment]
u see that march 13 is not monday but april 14 is monday

**Comment by oliviermorpa** [comment]
i forget: 
mars=march
Lun=Monday 
Mar= tuesday ...
:-)

**Comment by mgarin** [comment]
Looks weird, I will investigate this, thanks for reporting!

**Comment by oliviermorpa** [comment]
good pm,
did you solve this issue ?
customers are going crazy and do mistake...
Maybe i can help you ?
thanks and have a nice day

**Comment by mgarin** [comment]
I were able to find an issue with `setDate` method not updating the displayed month properly and it seems that it causes different issues depending on the usage case. I will add the fix for it pretty soon.

**Comment by mgarin** [comment]
I have added fix for this issue. Updated pre-release artifacts with this fix are now also available:
http://weblookandfeel.com/downloads/prerelease/
It will also be included in the v1.29 release later on.

**Comment by htetaungkhant** [comment]
WebDateField.setDate() does not update selection of calendar.

**Comment by mokun** [comment]
> WebDateField.setDate() does not update selection of calendar.

What does "selection of calendar" mean ?

I call setDate() frequently and it works fine. For instance,

`dateField.setDate(new Date(earthClock.getInstant().toEpochMilli()));`

**Comment by mgarin** [comment]
I've actually missed that comment, I'll re-check it. I think he meant that popup calendar doesn't update displayed selected date in that case, not the field itself.

**Comment by mgarin** [comment]
@htetaungkhant 
I weren't able to find any issues with updating `WebDateField` date in either field or calendar in it's popup. If you could provide a small code example I would be able to find and fix the issue. 

For now it seems that it was either in older version of the library or involved some tricky `WebDateField` usage. I'll close this again, but feel free to reopen.

Also I've added some minor improvements for popup hiding upon date/format change - #579
