### ISSUE TITLE
WebButton ToolTip hidden 

### ISSUE THREAD

**Issue by oliviermorpa** [mgarin/weblaf#261]
good pm,

when the Buton is just under the title Frame, then the tooltext is hidden

   jButton1.setToolTip("TRY", TooltipWay.up);

![capture d ecran 2015-03-27 a 16 28 42](https://cloud.githubusercontent.com/assets/9378538/6864568/5d2fea70-d49e-11e4-857a-4491c1aacfe3.png)

**Comment by mgarin** [comment]
This is unfortunately a limitation of current implementation of custom tooltips.
Those can only be displayed within root pane bounds.
I will be addressing related improvement in v1.30: #63
