### ISSUE TITLE
how to change title bar color

### ISSUE THREAD

**Issue by alipanwar** [mgarin/weblaf#275]
Dear mgarin,

There are two question:
1. How to change titlebar color?
2. How to make titlebar text shown while not focus, now the titlebar text only shown when the panel selected.

Thank you

**Comment by mgarin** [comment]
I am not sure what those questions are about - window decoration title bar? or some titled panel?
Could you provide a small code example where you weren't able to do the stuff you wanted to?

**Comment by alipanwar** [comment]
For question no 1. My app is like MDI application with menu, and I am using this code 
        StyleConstants.topBgColor = Color.BLUE;
        WebLookAndFeel.install();
the menu panel color changed to blue, but the title bar is not (still grey). is there a way to change the color of title bar.
        
For question no 2. i'm using vldocking and weblaf and apparently its vldocking issue, so case closed i think.

Thank you,

**Comment by mgarin** [comment]
- I'm still unsure which title bar you are talking about.<br>
If it's about window title bar - you can change it like this:
```java
WebRootPaneStyle.topBg = Color.BLUE;
```
- Well, I didn't really understand the issue there, but I guess its good if you have solved the issue or found the answer.

**Comment by mgarin** [comment]
In any case, with v1.29 release there will be more convenient way to skin everything and configure any settings used to paint components. I will be releasing multiply guides about that in [WIKI](https://github.com/mgarin/weblaf/wiki) here.
