### ISSUE TITLE
Disabled button text shade

### ISSUE THREAD

**Issue by iMichka** [mgarin/weblaf#282]
Hi

I noticed that the text in disabled buttons is not aligned with the text in enabled buttons. See first screen shot. This is annoying when you have buttons which are enabled/disabled on the same row, and especially when you enable/disable them, you see the text moving.

![button1](https://cloud.githubusercontent.com/assets/3406519/7698679/85daa530-fe12-11e4-85dc-942427044187.png)

This is due to a shade on the disabled text, which is visible when the background is changed. This problem is even more annoying with a dark background on buttons.

![button2](https://cloud.githubusercontent.com/assets/3406519/7698675/8215a760-fe12-11e4-81cc-cd46d91ee6e6.png)

- Could the text be drawn at the right place, so that it is aligned between enabled/disabled text.
- Can the shade color be changed ? (It is white for the moment, and the only way I found to change it is by using UIManager.put("Button.background", Color.XX), so I guess this shade is using the button's background.
- If it is not possible, could the shade just optionally be disabled ?

**Comment by mgarin** [comment]
Good point. And I also didn't like the way it is painted right now.
I will make enhancement to the way disabled text is panted in various components.

**Comment by mgarin** [comment]
I have included changes for this in the `styling` branch, so when it is released - texts should be displayed properly in the disabled state without shifting.

**Comment by mgarin** [comment]
I will add some more changes before the final v1.29 release.

**Comment by mgarin** [comment]
This is issue doesn't exist anymore since all buttons (and some other components) were changed to use `IContent` implementations for content painting. It can now be fully customized using the styling sytem.

**Comment by iMichka** [comment]
I can confirm that this is fixed. I changed the style of the different components and the shadows are now gone for me. Thanks
