### ISSUE TITLE
Style Manager: Panel Backcolor is not set (Need to get Rounded WebPanel from customStyle)

### ISSUE THREAD

**Issue by iamchathu** [mgarin/weblaf#287]
I have my skin define as below and worked well until i add boarder-pane style added.

Now it's working but boarder-pane background didn't change.

```xml
<skin>

...
    <!-- Separate style classes -->
    <style type="panel" id="default">
        <component>
            <foreground>255,255,255</foreground>
            <background>57,66,100</background>
        </component>
        <painter id="painter" class="com.alee.managers.style.skin.web.WebPanelPainter">
            <round>2</round>
            <shadeWidth>2</shadeWidth>
            <paintBackground>true</paintBackground>
            <webColoredBackground>true</webColoredBackground>
        </painter>
    </style>
    
    <!-- Custom panel styling with inner shade -->
    <style type="panel" id="inner-shade">
        <painter id="painter" class="com.alee.extended.painter.InnerShadePainter">
            <shadeWidth>10</shadeWidth>
            <round>2</round>
            <shadeOpacity>0.75</shadeOpacity>
        </painter>
    </style>a
    
    <style type="panel" id="boarder-pane">
        <component>
            <foreground>255,255,255</foreground>
            <background>155,89,182</background>
        </component>
        <painter id="painter" class="com.alee.extended.painter.BorderPainter">
            <width>1</width>
            <round>2</round>
            <color>155,89,182</color>
        </painter>
    </style>
    

</skin>
```

**Comment by iamchathu** [comment]
Added Style like below But Panel didn't get rounded corners.

```xml
...
<style type="panel" id="date-pane">
        <component>
            <foreground>255,255,255</foreground>
            <background>52,104,175</background>
        </component>
        <painter id="painter" class="com.alee.managers.style.skin.web.WebPanelPainter">
            <round>6</round>
            <shadeWidth>3</shadeWidth>
            <paintBackground>true</paintBackground>
            <webColoredBackground>true</webColoredBackground>
        </painter>
    </style>
```

**Comment by mgarin** [comment]
If settings aren't working in painter - you have to provide them in <ui></ui> block instead since it has copies of those settings and override painter settings. This behavior will be changed with the styling update, but with the current version it is necessary.

**Comment by mgarin** [comment]
Also, if using ui block doesn't help - probably it is a bug of the painter in the current main branch.

In any case, I already said a few times and will repeat - in currently available v1.29 pre-release version styling is not yet fully supported and has a lot of issues which are being addressed right now. I recommend not using it until I will merge the `styling` branch into `master`.

You can have a peek at the changes in the `styling` branch here:
https://github.com/mgarin/weblaf/tree/styling
It is now working, but still has a lot of issues to be fixed.

One of good things - there will be a clear and convenient way to style stuff - without looking back at the source code all the time. You will address painters and sometimes components in skin XML files, UIs will not copy the same settings anymore and will only have a few left which usually you won't need to modify.

You can look at some XML files here:
https://github.com/mgarin/weblaf/tree/styling/modules/ui/src/com/alee/managers/style/skin/web/resources
Those aren't final yet as well and there will be a few major enhancements, but they are now properly structured and have most settings included.

**Comment by iamchathu** [comment]
I'm using stable 1.28

**Comment by iamchathu** [comment]
I need to get rounded corner web panels. :cry:

**Comment by mgarin** [comment]
Then you might have to wait for the styling branch to be in pre-release.
And v1.28 is not really stable - it is pretty old and has a lot more issues than the pre-release:
http://weblookandfeel.com/downloads/prerelease/
