### ISSUE TITLE
Change font globally for InputPrompt

### ISSUE THREAD

**Issue by iamchathu** [mgarin/weblaf#293]
Is there way like

```java
    UIManager.put("ToolTip.font", new Font("Ubuntu", Font.PLAIN, 18));

```

to change font of InputPrompt in WebComponents ?

**Comment by mgarin** [comment]
There is only a way to change it for some specific type of components, for example text fields:
```java
WebTextFieldStyle.inputPromptFont = new Font("Ubuntu", Font.PLAIN, 18);
```
or password fields:
```java
WebPasswordFieldStyle.inputPromptFont = new Font("Ubuntu", Font.PLAIN, 18);
```
There is no way to set it globally for all components where those are used yet.

**Comment by iamchathu** [comment]
Do I have to put this before

```java
WebLookAndFeel.install();
```

?

**Comment by mgarin** [comment]
You need to add this before creating component which uses that value.

**Comment by iamchathu** [comment]
It's bit complicated since I have to lot of WebTextFields. Is there any way i can use style manager to set this?

**Comment by iamchathu** [comment]
I need a way like ```java UIManager.put("WebTextFields.inputFont",new Font("Ubuntu", Font.PLAIN, 18)); ```

**Comment by mgarin** [comment]
How is it complicated?
You can set it once and it will style all text fields created afterwards.
Just the same way UIManager does with all default options.

And no, this option isn't available in `StyleManager` yet.

**Comment by iamchathu** [comment]
My project is Netbeans one.In my project main class I set Look and feel to WebLAF. and execution is begun after is creating objects of JFrames.I add 

```java
WebTextFieldStyle.inputPromptFont = new Font("Ubuntu", Font.PLAIN, 18);
```

 there but it didn't apply to any :cry:

**Comment by mgarin** [comment]
You can set this option in the same place you setup L&F, there is no problem with that.
But this change should be done before the UI itself is initialized.

**Comment by iamchathu** [comment]
I Did like that.But I doesn't affect the my inputPromt Font :sob:

**Comment by mgarin** [comment]
That means that UI you have made using NetBeans initializes before that. I can't help with that unfortunately as this is one of the core things.

You have to either find a way (in NetBeans documentation or examples) how to do this call before UI initialization or just hand-craft your UI using pure Swing. Second option is generally a better way. I don't really recommend using any kind of builders as they are not good enough and put you into strict constraints like this one.

**Comment by iamchathu** [comment]
I try to Find a way to make this done and will update you with my Findings

**Comment by iamchathu** [comment]
This Code worked

```java
WebTextFieldStyle.round = 10;

```

It applied to all But Font :cry:

**Comment by iamchathu** [comment]
Found the problem.This do not work like 
```java
UIManager.put("ToolTip.font",new Font("Ubuntu", Font.PLAIN, 18));

```

I here i no mater what we put it will override the default fonts.

But in 

```java

WebTextFieldStyle.inputPromptFont = new Font("Ubuntu", Font.PLAIN, 18);

```

In component I have set the Font to different one so this setting will overridden by it.
