### ISSUE TITLE
HotKey Issue

### ISSUE THREAD

**Issue by iamchathu** [mgarin/weblaf#298]
When I Assign a HotKey from

```java
   btSearch.addHotkey(Hotkey.F2);

```

The actionPerform is triggered every time if press the F2 even though that Frame is at that moment blocked. 

In My scenario a JFrame has a SearchButon Later It open a dialog top Of it disabling access to JFrame. But if I press F2 there underlying blocked JFrame's Search action is triggers.

Is there any workaround for this?

**Comment by mgarin** [comment]
Hotkey added like you did is a global one, it will work across all windows in your application.
If you want to tie the hotkey to some specific container use this method:
```java
btSearch.addHotkey ( container, Hotkey.F2 );
```
You can pass a window there as well.

**Comment by iamchathu** [comment]
Wow great !!! Thanks for the support :+1:
