### ISSUE TITLE
Can not globally change OptionPane Button Text

### ISSUE THREAD

**Issue by iamchathu** [mgarin/weblaf#299]
Hi,

I tried using 

```java
        UIManager.put("OptionPane.messageFont", new Font("Ubuntu", Font.PLAIN, 18));
        UIManager.put("OptionPane.buttonFont", new Font("Ubuntu", Font.PLAIN, 18));
        UIManager.put("ToolTip.font", new Font("Ubuntu", Font.PLAIN, 12));
        UIManager.put("OptionPane.yesButtonText", "Yeap");
        UIManager.put("OptionPane.okButtonText", "Okey");
        UIManager.put("OptionPane.noButtonText", "Nope");
        UIManager.put("OptionPane.cancelButtonText", "Cancelo");
```

The Font is set to dialog but ButtonText did not changed.

**Comment by mgarin** [comment]
Fonts can be applied globally before L&F initialization into these fields in `WebLookAndFeel` class:
```
    // Text components fonts
    public static Font globalControlFont = WebFonts.getSystemControlFont ();
    public static Font buttonFont;
    public static Font toggleButtonFont;
    public static Font radioButtonFont;
    public static Font checkBoxFont;
    public static Font colorChooserFont;
    public static Font labelFont;
    public static Font listFont;
    public static Font panelFont;
    public static Font progressBarFont;
    public static Font scrollPaneFont;
    public static Font viewportFont;
    public static Font sliderFont;
    public static Font tabbedPaneFont;
    public static Font tableFont;
    public static Font tableHeaderFont;
    public static Font titledBorderFont;
    public static Font toolBarFont;
    public static Font treeFont;

    public static Font globalTooltipFont = WebFonts.getSystemTooltipFont ();
    public static Font toolTipFont;

    // Option pane font
    public static Font globalAlertFont = WebFonts.getSystemAlertFont ();
    public static Font optionPaneFont;

    // Menu font
    public static Font globalMenuFont = WebFonts.getSystemMenuFont ();
    public static Font menuBarFont;
    public static Font menuFont;
    public static Font menuItemFont;
    public static Font radioButtonMenuItemFont;
    public static Font checkBoxMenuItemFont;
    public static Font popupMenuFont;

    // Component's accelerators fonts
    public static Font globalAcceleratorFont = WebFonts.getSystemAcceleratorFont ();
    public static Font menuItemAcceleratorFont;
    public static Font radioButtonMenuItemAcceleratorFont;
    public static Font checkBoxMenuItemAcceleratorFont;
    public static Font menuAcceleratorFont;

    // Title components fonts
    public static Font globalTitleFont = WebFonts.getSystemTitleFont ();
    public static Font internalFrameFont;

    // Editor components fonts
    public static Font globalTextFont = WebFonts.getSystemTextFont ();
    public static Font comboBoxFont;
    public static Font spinnerFont;
    public static Font textFieldFont;
    public static Font formattedTextFieldFont;
    public static Font passwordFieldFont;
    public static Font textAreaFont;
    public static Font textPaneFont;
    public static Font editorPaneFont;
```
With future updates there will be a more convenient way to provide those.

Also I do not recommend using `UIManager` to change defaults directly because WebLaF doesn't use some of those at all and some are replaced to avoid various issues and UI inconsistance.

**Comment by iamchathu** [comment]
The font's Ok @mgarin 

Problem is text it not change "Yes" To "Yeap" in Yes Option :cry:

**Comment by mgarin** [comment]
Oh yeah, though buttons font was the issue, my bad :)

All text values which L&F usually provides are replaced with WebLaF translation for convenient usage. You can always replace any available translations with your own using `LanguageManager`. Just provide additional dictionary in code:
```java
WebLookAndFeel.install ();
LanguageManager.addDictionary ( GlobalConstants.class, "dictionary.xml" );
JOptionPane.showConfirmDialog ( null, "Are you sure?", "Confirm", JOptionPane.YES_NO_OPTION );
```
```xml
<Dictionary prefix="weblaf">
    <Dictionary prefix="optionpane">
        <record key="ok">
            <value lang="en" mnemonic="K">Okey</value>
        </record>
        <record key="cancel">
            <value lang="en" mnemonic="C">Cancelo</value>
        </record>
        <record key="yes">
            <value lang="en" mnemonic="Y">Yeap</value>
        </record>
        <record key="no">
            <value lang="en" mnemonic="N">Nope</value>
        </record>
    </Dictionary>
</Dictionary>
```
This will basically replace default English translation with your own for those buttons. 

You can also replace any other labels used inside of default L&F components (like file chooser) by providing replacement for appropriate complete language keys which are combined from dictionary prefixes and record key.

You can find the complete translation file in WebLaF sources: [language.xml](https://github.com/mgarin/weblaf/blob/master/modules/core/src/com/alee/managers/language/resources/language.xml)

You can find the complete `LanguageManager` guide here: [How to use LanguageManager](https://github.com/mgarin/weblaf/wiki/How-to-use-LanguageManager)

**Comment by iamchathu** [comment]
Thanks @mgarin It's works.

If I add to languages can i select one language when setting the look and feel (A Global Language)?

**Comment by iamchathu** [comment]
I found

```java
LanguageManager.setDefaultLanguage("en");
```
Is it correct?

**Comment by mgarin** [comment]
Yes, you can set language globally using that method. Just make sure you have overridden all language records required for all components you use in case you set language which is not supported by WebLaF by default.

List of supported languages can be found in [`LanguageConstants`](https://github.com/mgarin/weblaf/blob/master/modules/core/src/com/alee/managers/language/LanguageConstants.java) class.

By default WebLaF uses language provided by `System.getProperty ( "user.language" )` if it is in supported list, otherwise it uses English.
