### ISSUE TITLE
Change ForeColor in JFileChooser components label font color

### ISSUE THREAD

**Issue by iamchathu** [mgarin/weblaf#303]
![issue](https://cloud.githubusercontent.com/assets/3932230/8199238/8ce8e804-14cf-11e5-9a6d-c315cffd2f4b.png)

I need to change Font color to white in label inside JFileChooser Component. 

Is there anyway to do it like using UIManager.put(...) ?

Thank you.

**Comment by mgarin** [comment]
There is no access to this label right now.
But it will be restyleable with changes from final v1.29 release.

**Comment by mgarin** [comment]
This label along with other file chooser elements is now styleable through the XML similarly to other smaller components. You simply need to provide a style override in your custom skin or skin extension.
