### ISSUE TITLE
Internationalization support for WebDateField 

### ISSUE THREAD

**Issue by iamchathu** [mgarin/weblaf#305]
Can we change the Locale in WebDateField Components ?

Using ICU4j will be better.

**Comment by mgarin** [comment]
If you mean the `Locale` used to render date then you can simply provide a different date format. It can be passed into `WebDateField` directly using this method:
```java
public void setDateFormat ( final SimpleDateFormat dateFormat )
```
and you can provide any locale you like into that format.

**Comment by iamchathu** [comment]
It does not support for 

```java
com.ibm.icu.text.SimpleDateFormat
```

Which is extended from DateFormat

**Comment by mgarin** [comment]
Good point. I have added a small change to support `DateFormat` instead of `SimpleDateFormat`, it will be available in the v1.29 release version as well.

**Comment by iamchathu** [comment]
Great :+1:  Seems we will have great thing soon

**Comment by iamchathu** [comment]
Shall we put this to 1.29 milestone?

**Comment by mgarin** [comment]
Changed this to enhancement.
