### ISSUE TITLE
Always on top fails to keep the window on top

### ISSUE THREAD

**Issue by ArgonBird18** [mgarin/weblaf#312]
When a window in front of an always-on-top frame is redrawn, the always-on-top window goes behind the window that was just redrawn. When I am using the Window Builder plugin for Eclipse and I switch from Source to Design, an always-on-top window will move to the bottom. The frame I was using was look and feel decorated.

**Comment by mgarin** [comment]
Could you provide the code example that represents this issue?
I tried a few simple examples and all of them perform correctly.

Always-on-top is a standard Swing `Window` feature so it doesn't really matter whether you use it with or without WebLaF - it would perform in the same way in both cases. What might actually matter is that your window is undecorated - this might change this option behavior depending on the system you run application under. It will still perform in the same way with or without WebLaF.

**Comment by ArgonBird18** [comment]
It seems to be a bit of a system bug. I noticed the bug yesterday, and I rebooted my computer. Then after rebooting it I still saw the bug. Today I did the same thing that I did yesterday, and the window stayed on top. So I think that there was no bug, and rebooting my computer fixed it. Also I'm running Windows 8.1, and that may be a source of that problem.
