### ISSUE TITLE
ToolBar borderPainted property not respected

### ISSUE THREAD

**Issue by Sciss** [mgarin/weblaf#313]
Hi,

I would like to minimise the visual noise / space of `JToolBar`. It seems that `setBorderPainted(false)` and `setBorder(null)` have no effect.

**Comment by mgarin** [comment]
Unfortunately there is no way to remove decoration from `JToolBar` with standard options.
Also even with `WebToolBar` you can only choose between two predefined styles.

Starting with v1.29 release you will be able to completely re-style toolbar through skin settings and also remove all unwanted spaces and decoration itself.

**Comment by mgarin** [comment]
Also considering some custom Swing component options like `borderPainted` - a lot of those will not be supported anymore since the next update (if they were supported so far) due to the global changes to the way styling works.

**Comment by mgarin** [comment]
As a small side tip - in `styling` version you can provide custom J-component style ID through `putClientProperty` method - that feature was added in response to #148 request.

For example right now you can do this for the toolbar:
```java
toolbar.putClientProperty ( StyleId.STYLE_PROPERTY, "attached" );
```
or:
```java
toolbar.putClientProperty ( "styleId", "attached" );
```
To provide a more compact toolbar style.
And you can of course add your own specific style and use it instead.
