### ISSUE TITLE
Allow disabling JScrollPane's corner replacement by WebTableUI

### ISSUE THREAD

**Issue by renato** [mgarin/weblaf#320]
I've always used JXTable with other LAFs and it has a "setColumnControlVisible" method that enables a button in the JScrollPane upper right corner.

The method it uses to do that is:
`scrollPane.setCorner(JScrollPane.UPPER_TRAILING_CORNER,
                            getColumnControl());`

`getColumnControl()` returns a JButton instance.

It looks like the attached image:
![lubak](https://cloud.githubusercontent.com/assets/3530/8674292/5df9f700-2a13-11e5-9520-0fac16bd79d5.jpg)

However, when used with WebLAF, the control button doesn't end up in the corner.

Any idea why it's not working and/or any workaround?

**Comment by mgarin** [comment]
Probably because of `WebTableCorner` component being placed there for the sake of proper styling. Though it is strange, because if you set the option after creating the table - nothing stops `JXTable` from replacing the corner component.

I will add an option to allow disabling that corner, but the default button placed in that corner will still look ugly. Though starting with the next version you will be able to set style ID to that button to change its view so probably that won't be a big issue.

**Comment by renato** [comment]
Thank you.

I'm using a workaround, extending WebTableUI and overriding configureEnclosingScrollPaneUI, as it kept resetting the corner.

**Comment by mgarin** [comment]
Yep, this workaround should work for now.
I will post an update here as soon as the option to disable corner is available.

**Comment by mgarin** [comment]
Scroll pane corners are not replaced anymore if set.
This is working in snapshot builds of `styling` branch and will be available in the final v1.2.9 release.

You can also implement `ScrollPaneCornerProvider` interface in your component now to provide a custom corner component that will replace default ones.

**Comment by mgarin** [comment]
I tried various possible options and came to conclusion that forceful corners installation is unfortunately the most convenient behavior for most common cases, so I have returned it back in a slightly optimized form. Without it components will not be able to promote their own corner components.

What I offer as a solution is using `ScrollPaneCornerProvider` interface. 
If you have, as an example, `JXTable` - extend it with your own class and implement `ScrollPaneCornerProvider` where for `upperTrailing` corner you can provide component returned by table `getColumnControl ()` method. That should do the trick without breaking common corners for various components using scroll pane.
