### ISSUE TITLE
How to use StyleEditor

### ISSUE THREAD

**Issue by greg6614** [mgarin/weblaf#333]
Hi, I would like to know where I can find the StyleEditor tool if it's already available or if we have to wait another release.

Thx in advance.
Regards

**Comment by mgarin** [comment]
`StyleEditor` tool in currently available version is just a small "playground" for testing some of the styles and it is not suited for any real usage cases.

Its modified and completed version will be available with v1.29 final release. Guides on how to use it will be also available in wiki here.

**Comment by greg6614** [comment]
OK thank you but where can I find this small "playfround" ?

**Comment by mgarin** [comment]
I doubt it will be any use for you as it is not what you might actually think it is - it is just a small test application I used to check some ideas and create/fix some XML styles initially and which is actually already outdated in the currently available version. 

But if you want to try it so much - you can launch `com.alee.extended.style.StyleEditor` class and see for yourself :)
