### ISSUE TITLE
Unable to set file chooser to DIRECTORIES_ONLY selection mode

### ISSUE THREAD

**Issue by mgarin** [mgarin/weblaf#339]
Shortly, this option doesn't work on current pre-release build:
```java
filechooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
```
There is also no way to filter out files with a custom filter right now.

**Comment by mgarin** [comment]
This issue is fixed in a pre-release build available on the site.
That fix will also be included in the final v1.29 release.

**Comment by parkjohnston** [comment]
are pre-release builds on maven?

**Comment by mgarin** [comment]
There are no official releases of WebLaF on Maven at all so far, so no.
I will work on the Maven builds after the v1.29 release though.

**Comment by mgarin** [comment]
Snapshot builds are now actually available on maven:
https://oss.sonatype.org/content/repositories/snapshots/com/weblookandfeel/
