### ISSUE TITLE
Internal frame resizing

### ISSUE THREAD

**Issue by RobertBColton** [mgarin/weblaf#342]
JInternalFrames do not appear to be resizable.

**Comment by mgarin** [comment]
I am aware of this issue, it is actually already on this tracker: #27
It is getting addressed in the upcoming v1.29 update.
I will close this issue as it is generally a duplicate.

**Comment by RobertBColton** [comment]
Sounds reasonable.

**Comment by mgarin** [comment]
This is a bit unrelated to Internal frames, but anyway - yes, WebLaF window decoration doesn't have such issue. You can see how window decoration works with WebLaF by running demo application JAR which is available here in [releases section](https://github.com/mgarin/weblaf/releases) and on the [site](http://weblookandfeel.com/).

**Comment by RobertBColton** [comment]
I can confirm with the download from the other ticket that the original issue is resolved. JInternalFrames are now properly resizable and I see no other issue with them.
http://weblookandfeel.com/downloads/styling/

However, I should mention that the latter issue I mentioned does occur in another form. Apparently decorated window borders do not appear to be working
```java
		JFrame.setDefaultLookAndFeelDecorated(true);
		JDialog.setDefaultLookAndFeelDecorated(true);
```

**Comment by mgarin** [comment]
This specific bug is closed so I left the answer in your separate issue: #388
Let's have the conversation there :)

**Comment by RobertBColton** [comment]
That sounds good, my apologies as I was looking around to see if I had already filed it. I forgot that I included it here as a comment. I'm really sorry about that, GitHub search failed to bring me back here when I looked to see if "Unable to modify window decoration while it is displayed" was posted anywhere on your repo. I blame git :smile:
