### ISSUE TITLE
Baseline alignment JComboBox

### ISSUE THREAD

**Issue by RobertBColton** [mgarin/weblaf#344]
Baseline alignment does not appear to work.
https://docs.oracle.com/javase/tutorial/uiswing/layout/groupExample.html

Always seems to be top or left, completely ignoring when I have a combo with a text field or label using baseline alignment vertically.

**Comment by mgarin** [comment]
Can you provide a specific problematic example?

If you mean the one behind the link - it seems to be working properly:
![image](https://cloud.githubusercontent.com/assets/2361389/11115023/d69ec048-8939-11e5-9e97-ee516fdd302d.png)

WebLaF doesn't change anything in the layout behavior, it copies the Metal / Windows one and doesn't really add anything on its own.

**Comment by RobertBColton** [comment]
@mgarin Can you try again with a JComboBox? From my own application it seems to be only with ComboBox's and the same issue in both 1.28 and 1.29's beta.

From the same 1.29 screenshot of the program in #345 we can see none of the ComboBox's work with baseline alignment. Label's and text fields seem to be fine.
![LGM Web 1.29](https://cloud.githubusercontent.com/assets/3212801/11116471/d1916896-8900-11e5-8241-806d3fc2f85a.png)

**Comment by mgarin** [comment]
Yep, there is an issue if there with combobox:
![image](https://cloud.githubusercontent.com/assets/2361389/11116642/fb82676a-8944-11e5-9b9f-b2073a47d0a5.png)
But if something else is there like a button it is getting fixed:
![image](https://cloud.githubusercontent.com/assets/2361389/11116655/12a6a6a4-8945-11e5-94ef-7b01a2562626.png)
There might also be similar issues with some other components, I will investigate this.
Though the fix will probably be included only into the final v1.29 update release.

**Comment by RobertBColton** [comment]
@mgarin Excellent! Do you have an ETA of the 1.29 release? I am considering making this the defacto look and feel for this application.

**Comment by mgarin** [comment]
The will be ETA soon in update post on the site.
Keep an eye on it ;)

**Comment by RobertBColton** [comment]
@mgarin Will do! :D

**Comment by mgarin** [comment]
There was indeed an issue within `WebComboBoxUI` which caused this strange behavior.
Fix is already available in `styling` branch and will be included into final release.

**Comment by RobertBColton** [comment]
I can confirm this appears to be fixed in 1.29, our editors seem to have no problem with the baseline alignment now.

![Baseline Fixed 1.29](https://cloud.githubusercontent.com/assets/3212801/15264166/8b0bbe20-193e-11e6-9ffa-53591ec1df7e.png)

**Comment by mgarin** [comment]
Good to hear!

By the way, out of curiosity - on which OS/JDK versions were these screenshots taken? I am wondering because you're using custom frame decoration and yet text uses proper subpixel rendering which is something I couldn't achieve without ultra-dirty global workarounds.

**Comment by RobertBColton** [comment]
```
Microsoft Windows [Version 10.0.10586]
(c) 2015 Microsoft Corporation. All rights reserved.

C:\Users\Owner>java -version
java version "1.8.0_77"
Java(TM) SE Runtime Environment (build 1.8.0_77-b03)
Java HotSpot(TM) 64-Bit Server VM (build 25.77-b03, mixed mode)

C:\Users\Owner>ver

Microsoft Windows [Version 10.0.10586]

C:\Users\Owner>
```

It might be because my monitor is 2560x1440 and it's only 25" so very high DPI. I am not exactly sure how Swing handles DPI, or if it even does at all. I do know that Windows Forms just caches the application as a bitmap if it's not set as DPI aware and scales it up, but the end result of this is that it's usually very blurry. I can't really think of another cause for why it would be working.

**Comment by mgarin** [comment]
I doubt it is connected to the high DPI screen but probably to Windows 10 and latest JDK versions.

The point is - subpixel font rendering doesn't work when you are painting your text onto an image (graphics of an image) with alpha channel available. It simply gets disabled. And that is exactly the type of image used as a main UI storage behind the scenes when your frame is not opaque (that is the case with custom decoration enabled).

I'm not even sure if its a limitation of the technology or just a JDK bug, but that is how things work right now. At least should in most cases. Though your example seems to trick this thing and that is why I was curious :)
