### ISSUE TITLE
GroupLayout on JToolBar

### ISSUE THREAD

**Issue by RobertBColton** [mgarin/weblaf#345]
I use a group layout on a JToolBar with a text field that is supposed to fill the available area horizontally. Nothing is done other than create a default GroupLayout and setting it on the JToolBar. It works under every other look and feel. In web look and feel it is compact and looks as though it has 0 columns. It does respect setColumns, but does not seem to work with the GroupLayout default behavior. On a normal panel other than JToolBar it does behave as expected.
```Java
		filterPanel = new JToolBar();

		filterLayout.setHorizontalGroup(filterLayout.createSequentialGroup()
		/**/.addComponent(filterText)
		/**/.addComponent(prevButton)
		/**/.addComponent(nextButton)
		/**/.addComponent(searchInButton)
		/**/.addComponent(setButton));

		filterLayout.setVerticalGroup(filterLayout.createParallelGroup()
		/**/.addComponent(filterText)
		/**/.addComponent(prevButton)
		/**/.addComponent(nextButton)
		/**/.addComponent(searchInButton)
		/**/.addComponent(setButton));

		filterPanel.setLayout(filterLayout);
		filterPanel.setFloatable(true);
		filterPanel.setVisible(Prefs.showTreeFilter);
```

I've also realized I can simplify this code, originally it was to work around the GTK look and feel not stretching the text field. But this other way still doesn't work with Web L&F and I don't have a good idea as to why.
```Java
		// Use a toolbar so that the buttons render like tool buttons and smaller.
		filterPanel = new JToolBar();

		// Use a custom layout so that the filterText control will stretch horizontally under
		// all Look and Feels.
		BoxLayout filterLayout = new BoxLayout(filterPanel, BoxLayout.X_AXIS);

		filterPanel.add(filterText);
		filterPanel.add(prevButton);
		filterPanel.add(nextButton);
		filterPanel.add(searchInButton);
		filterPanel.add(setButton);

		filterPanel.setLayout(filterLayout);
		filterPanel.setFloatable(true);
		filterPanel.setVisible(Prefs.showTreeFilter);
```

**Comment by mgarin** [comment]
I took you last code example and tried running it:
```java
public class Test
{
    public static void main ( String[] args )
    {
        WebLookAndFeel.install ();

        // Use a toolbar so that the buttons render like tool buttons and smaller.
        JToolBar filterPanel = new JToolBar ();

        // Use a custom layout so that the filterText control will stretch horizontally under
        // all Look and Feels.
        BoxLayout filterLayout = new BoxLayout ( filterPanel, BoxLayout.X_AXIS );

        filterPanel.add ( new JTextField ( 1 ) );
        filterPanel.add ( new JButton ( "<" ) );
        filterPanel.add ( new JButton ( ">" ) );
        filterPanel.add ( new JButton ( "|" ) );
        filterPanel.add ( new JButton ( "X" ) );

        filterPanel.setLayout ( filterLayout );
        filterPanel.setFloatable ( true );

        TestFrame.show ( filterPanel, 50 );
    }
}
```
Seems to be working properly:
![image](https://cloud.githubusercontent.com/assets/2361389/11114886/eae69554-8938-11e5-9d2d-297639197d32.png)
or not?

**Comment by RobertBColton** [comment]
@mgarin Can you test again with 1.28? I am using 1.28, I'd love to test the 1.29 beta but I am unable to find it anywhere. Neither this or #344 are working for with 1.28, so I am venturing it has been since fixed.

**Comment by mgarin** [comment]
Well, v1.28 is really outdated and it contained a lot of critical issues which have been fixed since then. I will update the download section on the site as well with v1.29 a bit later so it will be more accessible.

I guess I will be closing this one then.
