### ISSUE TITLE
JTextField clipping area

### ISSUE THREAD

**Issue by RobertBColton** [mgarin/weblaf#346]
This is a minor issue. In my program I am subclassing JTextField to make a search bar with an overlay hint. Under the other look and feels the clipping area is properly setup automatically.

```Java
	@Override
	public void paintComponent(Graphics g) {
		super.paintComponent(g);
		if (hint != null && getText().length() == 0 && (!(hideOnFocus && hasFocus()))){
				int padding = (getHeight() - getFont().getSize())/2;

				// this allows the control to get the global property for antialiasing
				// thus making it affected by the preference in the preferences window
				Object map = Toolkit.getDefaultToolkit().getDesktopProperty("awt.font.desktophints");
				if (map != null) {
				    ((Graphics2D) g).addRenderingHints((Map<?,?>) map);
				}
				g.drawString(hint, 4, getHeight() - padding - 1);
		}
	}
```

Not the case with web look and feel, the area is not clipped and my text overflows onto other controls.
![Text Overflow](https://cloud.githubusercontent.com/assets/3212801/11118067/1808df28-890d-11e5-87e1-bcdd37f2c9e5.png)
This is clearly not a breaking issue, but is probably a simple tweak in one of the UI delegates. It's barely even noticeable but I feel it's better to report it than not to report it.

**Comment by RobertBColton** [comment]
Scratch that, not an issue, occurs in Nimbus look and feel too.

**Comment by renato** [comment]
I think I use WebTextField.setInputPrompt() for the very same result...

**Comment by mgarin** [comment]
Yep, as @renato says - you can use provided by WebLaF input prompt option in text field:
```java
final WebTextField textField = new WebTextField ( 25 );
textField.setInputPrompt ( "Enter word to search..." );
textField.setHideInputPromptOnFocus ( false );
```
Result will be this:
![image](https://cloud.githubusercontent.com/assets/2361389/11119289/78e20f44-8959-11e5-826e-0e9feadf7661.png)

**Comment by RobertBColton** [comment]
Thanks! I figured there was such as a control. Perhaps after 1.29's stable release i can look to committing the program to Web LaF, for now I am looking for backwards compatibility with the other look and feels.
