### ISSUE TITLE
JToolBar Horizontal Glue

### ISSUE THREAD

**Issue by RobertBColton** [mgarin/weblaf#347]
Both of the following appear on the left with no gap between them. This seems to be only an issue with Web look and feel.
```
		tool.add(new JButton("left"));
		tool.add(Box.createHorizontalGlue()); //right align after this
		tool.add(new JButton("right"));
```
This is usually the way this is done in Swing.
http://stackoverflow.com/questions/16230181/jtoolbar-insert-left-and-right

**Comment by mgarin** [comment]
That workaround for common Swing toolbar is not working because WebLaF uses a different toolbar layout. You can use constraints provided by `ToolbarLayout` to place toolbar elements conveniently with WebLaF:
```java
tool.add( new JButton("left") );
tool.add( new JButton("right"), ToolbarLayout.END );
```
Constraint `ToolbarLayout.START` is used by default.
There are totally four options:
```java
    /**
     * Positions component at the leading side of the container.
     */
    public static final String START = "START";

    /**
     * Positions component in the middle between leading and trailing sides.
     */
    public static final String MIDDLE = "MIDDLE";

    /**
     * Forces component to fill all the space left between leading and trailing sides.
     */
    public static final String FILL = "FILL";

    /**
     * Positions component at the trailing side of the container.
     */
    public static final String END = "END";
```

If you want it to work the way it usually does - simply set:
```java
new BoxLayout(JToolBar.this, BoxLayout.LINE_AXIS)
```
```java
new BoxLayout(JToolBar.this, BoxLayout.PAGE_AXIS)
```
as toolbar layout for horizontal and vertical ones accordingly.

And yes, this is an intended change to provide better toolbar functionality :)

**Comment by RobertBColton** [comment]
That seems to throw addSeparator for a loop. It divides the available area among the separators and the horizontal glue.

![Separator BoxLayout](https://cloud.githubusercontent.com/assets/3212801/11119294/7930a106-8916-11e5-92dd-4dc9f76d639a.png)

**Comment by mgarin** [comment]
This is something interesting actually, I have a similar issue with common separator with Metal L&F:
```java
public class Test
{
    public static void main ( String[] args )
    {
        JToolBar toolBar = new JToolBar ();
        toolBar.setLayout ( new BoxLayout ( toolBar, BoxLayout.LINE_AXIS ) );
        toolBar.add ( new JButton ( "left" ) );
        toolBar.add ( new JSeparator ( WebSeparator.VERTICAL ) );
        toolBar.add ( new JButton ( "left" ) );
        toolBar.add ( Box.createHorizontalGlue () ); //right align after this
        toolBar.add ( new JButton ( "right" ) );
        toolBar.add ( new JSeparator ( WebSeparator.VERTICAL ) );
        toolBar.add ( new JButton ( "right" ) );
        TestFrame.show ( toolBar, 50 );
    }
}
```
Resulting frame is:
![image](https://cloud.githubusercontent.com/assets/2361389/11119695/6153a45c-895c-11e5-934a-1468df4b2825.png)
I will investigate this issue later on, need to finsih other stuff right now.

**Comment by RobertBColton** [comment]
Try addSeparator() as well. That is definitely because I am not getting that with Metal, my separators take up space under that one but they aren't ever actually visible (I mean the 1px vertical line is invisible). And they also don't take up as much space as your screenshot. I know separators were not very consistent in their implementation for Swing.

**Comment by mgarin** [comment]
I have added a fix for this issue into `styling` branch.
It will be available along with the final v1.29 release.

The problem was in the custom preferred size provided from the UI for all container components which was disabling container layout size calculations.

**Comment by RobertBColton** [comment]
With the download you linked in the other issue, I am still able to reproduce this. It occurs only when setting a BoxLayout on the toolbar. Creating horizontal glue has no effect on whether it occurs.
```java
tool.setLayout(new BoxLayout(tool, BoxLayout.LINE_AXIS));
```
![Toolbar BoxLayout](https://cloud.githubusercontent.com/assets/3212801/15264381/9c292a2e-1940-11e6-96e1-05ef72cb2a1c.png)

**Comment by mgarin** [comment]
I will check this again

**Comment by mgarin** [comment]
I have pushed a fix for this issue, it should solve problem with separators. 

Though there are still some inconsistencies which I might not be able to fix until the major rehaul of the way sizes are defined within components, UIs and painters.

**Comment by RobertBColton** [comment]
This one does not appear to have been resolved with the latest snapshot from yesterday. I'm getting exactly the same results when setting a box layout with or without the horizontal glue.

**Comment by mgarin** [comment]
Yes, it was not included in yesterday's snapshot - it will be out slightly later today.

**Comment by RobertBColton** [comment]
I can confirm with the latest snapshot of 1.29 that this issue has been resolved. Thanks!
http://weblookandfeel.com/downloads/styling/

![BoxLayout](https://cloud.githubusercontent.com/assets/3212801/15363971/9ff4a466-1ce8-11e6-8754-089d6dfb4230.png)
