### ISSUE TITLE
Replaceable icons set

### ISSUE THREAD

**Issue by mgarin** [mgarin/weblaf#348]
There is already a huge set of icons used within WebLaF and there is no convenient way to replace them altogether or sometimes there is no way to replace them at all.

This should certainly be addressed along with introduction of the fresh UI icons set based on SVG images in addition to existing PNG images set.

It is also a good opportunity to get rid of some deprecated or/and unused icons within library to reduce its size and make it cleaner overall.

**Comment by iamchathu** [comment]
+1

Great feature

**Comment by chaddaniels** [comment]
Have you considered adding something similar to FontAwesomeFX?  It is a JavaFX library that allows the use of scalable font characters from FontAwesome as images.  If you're unfamiliar, see:
https://bitbucket.org/Jerady/fontawesomefx

**Comment by mgarin** [comment]
I did look into it briefly, but I am pretty sure there are some issues/limitations with fonts in older JDK versions - remember that WebLaF supports JDK 6 update 30 +. 

They do have SVG version for the glyphs though which I might actually implement at some point since I am working towards scaleable SVG images as a replacement for non-scaleable raster images because they have a good potential:

- They can be scaled, recolored and modified in runtime
- They are stored in readable XML files
- They work fast when used properly

You can actually already see some SVG icon being used in new demo application from the `styling` branch and they work pretty well I should say.

Anyway, implementation of FontAwesome and similar things is certainly not something that will be around soon as it will take some significant time and will have to be constantly supported.

**Comment by mgarin** [comment]
This feature will be provided by `IconManager` [basic implementation](https://github.com/mgarin/weblaf/blob/styling/modules/ui/src/com/alee/managers/icon/IconManager.java) of which is now available in `styling` branch. Right now it is simply a sketch of future manager and is not used anywhere.

Also while working on the v1.29 release I got a small idea that might enhance this feature even further - allow providing icons within the skin files. That will be a pretty nice addition to `IconManager` itself. Basically you will be able to specify icons at any point in the skin XML:
```xml
<skin>
    ...
    <SvgIcon id="spinner-up" src="icons/spinner-up.svg" />
    <ImageIcon id="spinner-down" src="icons/spinner-down.png" />
    ....
</skin>
```
And then use it within the skin description:
```xml
<style type="button" id="next" extends="button">
    <component>
        <icon>spinner-up</icon>
    </component>
    ...
</style>
```

**Comment by mgarin** [comment]
First preview of `IconManager` and `IconSet`s have been added in v1.2.9 update. It will receive major improvements in the next few updates to include most of the features mentioned in this issue.

**Comment by mgarin** [comment]
Last week I've started looking into `IconManager` and adjusting some stuff for wiki (by recent request from @mokun) and I've gone into some major internal adjustments across the whole library. 

As a result of these changes (that will be going live today):

- Icons provided through skins and extensions are not added directly into `IconManager` anymore so they can't be accidentally removed or replaced, but all icons from the active skin and extensions are available through the same `IconManager` API.

- All `IconSet` caches are now properly updated on demand in `IconManager` allowing proper override of any particular icon by simply providing a new `IconSet` with an icon that uses existing identifier.

- `IconSet`s will now have a strict priority order:
  User-added sets > Extensions sets > Skin sets

- Icons within `IconSets` will now also have a strict priority order:
  Later added icons > Earlier added icons

- There are multiple performance and API improvements for `IconManager`, `IconSet`, `IconData` as well as related utilities like `ImageUtils` and various other classes.

All these changes will basically allow any existing icons from `IconSets` to be replaced through either custom `IconSet`s added in extensions or at runtime.

**Comment by mgarin** [comment]
I'll be posting more extensive guide on wiki once snapshot versions with these changes are available.

**Comment by mgarin** [comment]
All icons provided through `IconSet`s are now easily replaceable.

To do that - you simply need to provide icon with the same identifier in another set and add it later than the first set have been added with an exception of skin/extension `IconSet`s - those always have lower priority as was mentioned above.

There is also a new `RuntimeIconSet` available for creating custom `IconSet`s in runtime with ease. Also `SvgIconData` and `ImageIconData` now both have convenient public constructors asking for all necessary parameters.

**Comment by mgarin** [comment]
Detailed article with all information about these changes can be found on wiki:
https://github.com/mgarin/weblaf/wiki/How-to-use-IconManager
