### ISSUE TITLE
Weird code in WebProgressBarUI.getPreferredInnerVertical()

### ISSUE THREAD

**Issue by bspkrs** [mgarin/weblaf#353]
Is it intentional to set the dimension height to the preferredProgressWidth?

https://github.com/mgarin/weblaf/blob/master/modules/ui/src/com/alee/laf/progressbar/WebProgressBarUI.java#L408

**Comment by mgarin** [comment]
Yes, because it is the height of the vertical scroll bar, not horizontal one. And preferred width setting is working for both cases equally - you don't really want to have a super-wide vertical scroll bar, do you?

**Comment by bspkrs** [comment]
Ah, I get it now... thanks for the explanation.

**Comment by mgarin** [comment]
You are welcome :)
