### ISSUE TITLE
Jericho HTML parser 3.4 is not Java 6 compatible

### ISSUE THREAD

**Issue by Sciss** [mgarin/weblaf#359]
I just tried to build under Java 6, and at least using the Maven Central published version of the Jericho HTML parser for version 3.4 is bytecode incompatible. So I think it's better to revert to 3.3.

**Comment by mgarin** [comment]
I didn't use newer (3.4) version Jericho HTML parser - it is still 3.3 even in the `styling` branch. So I'm not really sure where I should revert it :)

**Comment by mgarin** [comment]
It is 3.3 even in the `pom.xml` - just checked.

**Comment by mgarin** [comment]
Just as an additional proof:

In sources: 
jericho-html-3.3.jar

In pom.xml:
```xml
        <dependency>
            <groupId>net.htmlparser.jericho</groupId>
            <artifactId>jericho-html</artifactId>
            <version>3.3</version>
        </dependency>
```

So WebLaF is certainly using 3.3 version :)
