### ISSUE TITLE
Add dockable pane and dockable frame components

### ISSUE THREAD

**Issue by mgarin** [mgarin/weblaf#37]
Add WebDockablePane and WebDockableFrame components.

**Original request:**
http://weblookandfeel.com/forum/viewtopic.php?f=2&t=61

**Comment by j9hamon** [comment]
I'm really interested in this feature (and maybe some other components as they look great). I tried the example in the WebDockablePane but it seems there is no way to move the frames (or maybe I don't understand how it works).
 
When do you plan to release the next version of WebLaF?

**Comment by mgarin** [comment]
As soon as possible, working on the release changes right now.

`WebDockablePane` which was in the code so far was simply a placeholder and will have nothing common with the final dockable pane component. Its actual implementation will be available shortly before the release.

**Comment by mgarin** [comment]
Base dockable framework implementation is now available in `styling` branch source code.
It does not have all of the common docking features yet, but the missing ones will be added quite soon.

Snapshots with all latest changes are always available here:
http://weblookandfeel.com/downloads/styling/
https://oss.sonatype.org/content/repositories/snapshots/com/weblookandfeel/

I will also add a wiki article about docking components usage soon.

**Comment by mgarin** [comment]
I have added an introduction guide on docking framework usage on wiki:
https://github.com/mgarin/weblaf/wiki/How-to-use-WebDockablePane

**Comment by mgarin** [comment]
Dockable framework is now fully available and all features planned for v1.2.9 release are already there and you could try them out on the snapshot builds.

@chaddaniels Coming back a bit at our discussion - I have tried to implement IntelliJ Idea dockable layout at first but it was a failure in a lot of ways:

1. Due to its static nature of frame positioning I have to hardcode those positions and frames behavior which leaves no room for future improvements
2. There are indeed a few inconvenient things with that layout which you have mentioned, and me and my colleagues found those too important to ignore
3. The whole layout is good for simple cases, but terrible for some more complex cases and that will force you to use a different framework in the end

Plus some other minor code and layout -related problems I have encountered while trying to implement simple layout.

So in the end I went with a complex layout used in a lot of applications. For inspiration I used latest Visual Studio and Jide docking frameworks. Of course I tried to exclude most inconvenient features and keep everything good. There are still some minor things to be tweaked but I think it is already quite good to be worth using. We already included it in dev branches of our commercial apps and had mostly good feedback so far :)

But anyway, feel free to try it out and post your feedback and/or improvement suggestions - those are always welcome!

**Comment by mgarin** [comment]
Grouping feature will be available in the next v1.3.0 update: #397

**Comment by mgarin** [comment]
Update v1.2.9 is live and dockable framework is now officially available.
