### ISSUE TITLE
WebInternalFrame or JInternalFrames Resize Issue

### ISSUE THREAD

**Issue by RoshanGerard** [mgarin/weblaf#375]
Monitor Resolution: 1366x768, 96DPI
It;s really hard to re-size an internal frame using mouse, i can only re-size by top, or right side edges of the frame and finding re-size edge with mouse pointer is hard.

**Comment by mgarin** [comment]
Which version of WebLaF did you use to run your application with internal frame?

There were quite a few issues with internal frames including resize issue which have been addressed in `styling` branch not long ago. Those changes aren't officially released yet and only available in snapshots repository: https://oss.sonatype.org/content/repositories/snapshots/com/weblookandfeel/

**Comment by RoshanGerard** [comment]
I'm using v1.29

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DDB4FAA8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by mgarin** [comment]
I guess it was pre-release v1.29 from the site download section?
If yes - it still contains those issues as it is a pretty old version.

You can try out the newest version [from here](http://weblookandfeel.com/downloads/styling/) or from the [snapshot repository](https://oss.sonatype.org/content/repositories/snapshots/com/weblookandfeel/) - this version already include fixes for internal frames and a lot more. However be aware that it has lots of changes made to the core WebLaF systems and APIs. It is basically a snapshot version from the current `styling` branch state which is fairly stable but still not ready for the final release.
