### ISSUE TITLE
WebImage paints outdated lastPreviewImage after new image was set

### ISSUE THREAD

**Issue by abika** [mgarin/weblaf#379]
Hi,
(v1.28) after setting a new image in a `WebImage` with `webImage.setImage()` the previous set old image is still painted. Happens only if display type is `setDisplayType(DisplayType.fitComponent)`.

Here is the code to reproduce:
```
import com.alee.extended.image.DisplayType;
import com.alee.extended.image.WebImage;
import com.alee.laf.rootpane.WebFrame;
import com.alee.utils.swing.EmptyMouseAdapter;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Graphics2D;
import java.awt.event.MouseEvent;
import java.awt.image.BufferedImage;

final class TestWebImage {
    public static void main(String[] args) {
        WebFrame frame = new WebFrame();
        frame.setSize(200, 200);

        final WebImage webImage = new WebImage().setDisplayType(DisplayType.fitComponent);
        webImage.setImage(createImage(Color.RED, 400));
        webImage.addMouseListener(new EmptyMouseAdapter(){
            @Override
            public void mouseClicked(MouseEvent e) {
                webImage.setImage(createImage(Color.GREEN, 400));
            }
        });
        frame.add(webImage, BorderLayout.CENTER);
        frame.setVisible(true);
    }

    static BufferedImage createImage(Color color, int size) {
        BufferedImage img = new BufferedImage(size, size, BufferedImage.TYPE_INT_RGB);
        Graphics2D graphics = img.createGraphics();
        graphics.setColor(color);
        graphics.fillRect(0, 0, size, size);
        return img;
    }
}
```

(and a quick workaround to see the new image: `webImage.setEnabled(false); webImage.setEnabled(true);`

**Comment by mgarin** [comment]
There was indeed an issue with preview image update behavior - `lastPreviewImage` field was not updated properly on image change. I have pushed a quick fix into `styling` branch.

Though I should say that v1.28 is quite outdated version of WebLaF and it contains a lot of other issues so I would recommend you to switch to either v1.29 that can be found on the site right now - that is the last build of `master` branch currently available - or straight to one of `styling` branch snapshots which can either be found [here](http://weblookandfeel.com/downloads/styling/) or in the [snapshot repository](https://oss.sonatype.org/content/repositories/snapshots/com/weblookandfeel/).

I am slowly adapting all wiki guides for that version and will keep releasing more guides on the new stuff available in that version. It has a lot of internal and API changes, but you should certainly give it a try as this is what WebLaF will be shifting towards in the future.

**Comment by mgarin** [comment]
I have also updated the [site version](http://weblookandfeel.com/downloads/styling/) of `styling` branch snapshot with this fix for `WebImage`.

**Comment by abika** [comment]
Great. 
Didn't know about the pre-releases of 1.29 and the styling branch but I need a solution with Maven/Gradle repo support. So for now I'll stick with 1.28 and wait until 1.29 is final, which is totally fine for me.

Guess, I close this now. And thanks for all your work!

**Comment by mgarin** [comment]
>  I need a solution with Maven/Gradle repo support

Snapshots are available in maven snapshots repository:
https://oss.sonatype.org/content/repositories/snapshots

Dependency for the snapshot usage:
```xml
<dependency>
    <groupId>com.weblookandfeel</groupId>
    <artifactId>weblaf-ui</artifactId>
    <version>1.2.9-SNAPSHOT</version>
</dependency>
```

**Comment by mgarin** [comment]
Latest snapshot there already contains the fix by the way.
