### ISSUE TITLE
JInternalFrame remove icon

### ISSUE THREAD

**Issue by RobertBColton** [mgarin/weblaf#383]
We first discovered this in our own application.
https://github.com/IsmAvatar/LateralGM/issues/263

I decided to report the issue to OpenJDK:
https://bugs.openjdk.java.net/browse/JDK-8154855

The inconsistency is currently set to be fixed in JDK 9. The issue is that setFrameIcon(null) should not only make the icon invisible, but also adjust the title bar layout so the space where the icon was originally at, is no longer empty space. So when there's no icon the title/text should start where the icon would have. The only look and feel that currently respects this is the default Swing cross-platform look and feel. Even the native Windows look and feel does not respect a null icon in its layout, making it inconsistent with the actual native platform MDI Windows (which I reported and should be fixed in JDK9).

I am also able to reproduce this issue with the Web L&F.
![JInternalFrame No Icon Layout](https://cloud.githubusercontent.com/assets/3212801/15264742/f81e22ea-1944-11e6-97fd-c846caf1c374.png)

**Comment by mgarin** [comment]
Thanks for reporting! 
I'll fix the layout of the title bar so the title will properly adjust its position.

Also, this is actually something I messed on my own even though similar issue might be found in other look and feel libraries :)

**Comment by RobertBColton** [comment]
Thanks! It does appear in the other look and feels too. My main complaint in the bug report I linked to OpenJDK was with how the system look and feel was inconsistent with Win32. If you did not want to change Web L&F I think that would be fine. I just think that moving the title to give it more room since the icon isn't there is just smarter.

**Comment by mgarin** [comment]
Actually, after looking into the `styling` code - this have been fixed a while ago, but it is only available in v1.2.9 snapshot builds now and will be in the final release as well.

Though by default starting with v1.2.9 title is now centered in the default window custom decoration:
![image](https://cloud.githubusercontent.com/assets/2361389/15289292/fb149402-1b79-11e6-9c15-662523bd269a.png)
You can easily change it in your custom extension or skin:
![image](https://cloud.githubusercontent.com/assets/2361389/15289326/307b7070-1b7a-11e6-91b2-2748f3e2f013.png)
And this is how it looks without icon:
![image](https://cloud.githubusercontent.com/assets/2361389/15289320/26274086-1b7a-11e6-92fb-eaa37cc0a386.png)

**Comment by RobertBColton** [comment]
Is that supposed to be the case with the snapshot available here?
http://weblookandfeel.com/downloads/styling/

It does not appear to be centered for me on JInternalFrames.

**Comment by mgarin** [comment]
Oops, I was checking out another issue related to normal (native system) windows and got a bit confused. I'll re-check this issue for `JInternalFrame` since it has different title implementation.

**Comment by mgarin** [comment]
I have made some general cleanup and update for the `JInternalFrame` title pane code - it is now very similar to `JFrame` decoration. Icon will not take extra space anymore if it is set to `null`.

This change will be available in a snapshot build later today.

**Comment by RobertBColton** [comment]
The title does appear to be centered now, but one thing I noticed is I don't think it's removing the padding. It is removing the icon and giving the title that much extra space, but it keeps the left and the right padding, so the title doesn't start at the same left inset that the icon would because it still has the right padding it seems.

I've drawn onto this screencap to show what I mean. The right picture should only have red as the inset instead of red and green.
![Centered Title Left Inset](https://cloud.githubusercontent.com/assets/3212801/15312778/d1482502-1bd4-11e6-8999-df77dfe4abd8.png)

**Comment by mgarin** [comment]
The problem here is that icon and title are different components due to the way they have to be placed sometimes. Icon component doesn't get removed when icon becomes `null` - it simply uses a zero size. This is true for frames/dialogs with custom decoration and internal frames. 

I'm pretty sure there was a reason to keep the icon, but probably it is no more. I will see whether it could be removed there or not.

Either way - I might keep some additional distance to the left from the text even with the fix because you always want to have slightly larger spacing at the left and right sides of the text.

**Comment by RobertBColton** [comment]
Actually, I would say this is not an issue. I went back and looked at the image again, the insets are consistent on the left and right when the icon is removed.

![Consistent Left and Right Insets](https://cloud.githubusercontent.com/assets/3212801/15318026/1027625c-1bf2-11e6-80fc-2cb6d6d4fa9e.png)

I'll leave it up to you to decide to close this, I just wanted to make sure I mentioned it.

**Comment by mgarin** [comment]
Also I've recently found one more issue with `BasicInternalFrameUI` - upon internal frame resize it switches off glass pane which negatively affects some of WebLaF components.

**Comment by mgarin** [comment]
Posted a bit more details in #461
I will be fixing this issue and #461 in the next few updates

**Comment by mgarin** [comment]
I just re-checked, all paddings & margins in the header are now in the style and can be customized, so there shouldn't ever be any random spacings between elements anymore.

That being said, default skin will still have 10px padding when positioned at left side without icon since it looks better that way. Smaller padding just looks wrong in that scenario.

Regarding resize issue #461 - i'll try to make a fix for it in v1.2.10
