### ISSUE TITLE
TabbedPane with SCROLL_TAB_LAYOUT not styled

### ISSUE THREAD

**Issue by iMichka** [mgarin/weblaf#395]
TabbedPanes are not styled when using the following option:
```
setTabLayoutPolicy ( WebTabbedPane.SCROLL_TAB_LAYOUT );
```

This is not something I need (I am not using it), and probably also not something anybody is using. When you have not enough space and too many tabs, it's better to find another concept than to use this option. So this is a very low-priority bug, but I thought it would be good to let you know.

**Comment by mgarin** [comment]
There is a list of issues with tabbed pane I am aware of including this one: #35

Tabbed pane is the next priority for me, so it will be changed quite soon to support painters and decorations. All bugfixes and possible new features will also come with those changes..

**Comment by iMichka** [comment]
Sorry to have opened a somewhat duplicated issue for this.
Thanks.
