### ISSUE TITLE
Tooltips doesn't appear after window (Frame) lost and regain focus

### ISSUE THREAD

**Issue by kandrakah** [mgarin/weblaf#404]
During the creation of the window, I found the following bug using TooltipManager class (com.alee.managers.tooltip.TooltipManager):
When the window loses focus (another window opens and closes later, for example) the initial window fails to display the tips, even forcing his appearance (TooltipManager.showTooltips (Component)).

Here the tip appears.
![bug001](https://cloud.githubusercontent.com/assets/817169/17939786/8c59b178-6a02-11e6-8e4d-fc42e7fe0ef4.jpg)

After the window lose and regain focus, no.
![bug002](https://cloud.githubusercontent.com/assets/817169/17939787/8c606d60-6a02-11e6-8041-1ece0d98aadb.jpg)

**Comment by mgarin** [comment]
A few things important to reproduce the case:
- How did you exactly register the tooltip on that field?
- What is that window exactly is - JDialog? JFrame? JWindow? a WebPopOver or something else?

**Comment by mgarin** [comment]
Also I just noticed that you are probably using v1.28 or pre-styling v1.29 version - which are both quite outdated - is that the case?

**Comment by kandrakah** [comment]
This window is a JInternalFrame and the fields have tooltips defined with the following code:

`public static void addToolTip(JComponent field, String message, TooltipWay position, int delay) {
        TooltipManager.setTooltip(field, message, position, delay);
    }`

I tested in both versions (1:28 and 1:29) and the bug is persistent. I did't get to test the current version on github for some changes in the code would be required (because of the style system changes).

I had suspected an implementation of JInternalFrame class (ModalityInternalFrame extends WebInternalFrame) to use to add the option to modal windows, but the problem persists even with the loss of focus for the JOptionPane / WebOptionPane messages.

**Comment by mgarin** [comment]
So if I understand it correctly, this is the order of actions to reproduce the issue:

1. Open a frame with desktop pane which contains internal frame with a field with a custom tooltip
2. Hover the field - tooltip is there, everything is working fine
3. Open a new frame in runtime and switch focus into that frame
4. Switch focus back to the initial frame
5. Hover the field - tooltip doesn't appear, something is broken

Or you were talking about multiple internal frames?

**Comment by mgarin** [comment]
Also as a side note - I might not be able to provide an update for older library version, but new version most probably already contains a fix for this problem, still need to confirm that though.

**Comment by kandrakah** [comment]
Correct.

A InternalFrame can open another to add something (a list of customers to select or something) but can also display only a dialogue (JOptionPane / WebOptionPane).

In both cases, the problem arises.

To try to correct, was tried a layout update (updateUI () and repaint () in JInternalFrame). There was no effect. The problem can only be solved by closing and reopening the frame.

My goal is just to report a problem I encountered. Will change to the newest version later.

**Comment by mgarin** [comment]
I made a small example to test the steps we discussed above:
```java
public class InternalFrameTooltipIssue
{
    public static void main ( final String[] args )
    {
        WebLookAndFeel.install ();

        final JDesktopPane pane = new JDesktopPane ();

        final JInternalFrame internal1 = new JInternalFrame ( "Frame 1", true, true, false, false );
        internal1.setLayout ( new VerticalFlowLayout () );

        final JTextField field = new JTextField ( 20 );
        TooltipManager.setTooltip ( field, "Sample tooltip", TooltipWay.down );
        internal1.add ( field );

        final JButton newInternal = new JButton ( "Open frame" );
        newInternal.addActionListener ( new ActionListener ()
        {
            @Override
            public void actionPerformed ( final ActionEvent e )
            {
                final JInternalFrame internal2 = new JInternalFrame ( "Frame 2", true, true, false, false );
                internal2.add ( new JLabel ( "Test label", JLabel.CENTER ) );
                internal2.setBounds ( 150, 150, 200, 300 );
                internal2.setVisible ( true );
                pane.add ( internal2 );
            }
        } );
        internal1.add ( newInternal );

        final JButton newOption = new JButton ( "Open option pane" );
        newOption.addActionListener ( new ActionListener ()
        {
            @Override
            public void actionPerformed ( final ActionEvent e )
            {
                JOptionPane.showMessageDialog ( pane, "Sample option pane" );
            }
        } );
        internal1.add ( newOption );

        internal1.setBounds ( 50, 50, 200, 300 );
        internal1.setVisible ( true );
        pane.add ( internal1 );

        final JFrame frame = new JFrame ( "Frame" );
        frame.add ( pane );
        frame.setSize ( 1000, 800 );
        frame.setLocationRelativeTo ( null );
        frame.setDefaultCloseOperation ( WindowConstants.EXIT_ON_CLOSE );
        frame.setVisible ( true );
    }
}
```
That certainly works correctly on the `styling` branch version and doesn't have any issues with displaying the tooltip. I'm not yet sure about the previous versions.

Could you run this small example and see if the issue still appears in it for you?

**Comment by kandrakah** [comment]
I ran the example with 1.28 library and there were no problems. I added the class that implements the Modal function to the example and the bug begins to emerge. I believe the problem is related to the modal function InternalFrames (which does not exist natively).

I'll check the ModalityInternalFrame class to see which code may be causing the failure, but, apparently is not something related to the library itself (since in normal situations the failure does not occur).

Example with changes: JComponents to Web components.

`public class InternalFrameTooltipIssue {

    public static void main(final String[] args) {
        WebLookAndFeel.install();

        final WebDesktopPane pane = new WebDesktopPane();

        
        final WebInternalFrame internal1 = new ModalityInternalFrame(pane, "Frame 1", true, true, false, false);
        internal1.setLayout(new VerticalFlowLayout());

        final WebTextField field = new WebTextField(20);
        TooltipManager.setTooltip(field, "Sample tooltip", TooltipWay.down);
        internal1.add(field);

        final WebButton newInternal = new WebButton("Open frame");
        newInternal.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(final ActionEvent e) {
                final WebInternalFrame internal2 = new ModalityInternalFrame(internal1, "Frame 2", true, true, false, false);
                internal2.add(new WebLabel("Test label", WebLabel.CENTER));
                internal2.setBounds(150, 150, 200, 300);
                internal2.setVisible(true);
                pane.add(internal2);
            }
        });
        internal1.add(newInternal);

        final WebButton newOption = new WebButton("Open option pane");
        newOption.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(final ActionEvent e) {
                WebOptionPane.showMessageDialog(pane, "Sample option pane");
            }
        });
        internal1.add(newOption);

        internal1.setBounds(50, 50, 200, 300);
        internal1.setVisible(true);
        pane.add(internal1);

        final WebFrame frame = new WebFrame("Frame");
        frame.add(pane);
        frame.setSize(1000, 800);
        frame.setLocationRelativeTo(null);
        frame.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        frame.setVisible(true);
    }
}`

Class that implements the Modal.

`public class ModalityInternalFrame extends WebInternalFrame {

    protected JDesktopPane desktopPane;
    protected JComponent parent;
    protected ModalityInternalFrame childFrame;
    protected JComponent focusOwner;
    private boolean wasCloseable;

    public ModalityInternalFrame() {
        super("", false, true);
        init();
    }

    public ModalityInternalFrame(JComponent parent) {
        this(parent, null);
    }

    public ModalityInternalFrame(JComponent parent, String title) {
        this(parent, title, false);
    }

    public ModalityInternalFrame(JComponent parent, String title, boolean resizable) {
        this(parent, title, resizable, false);
    }

    public ModalityInternalFrame(JComponent parent, String title, boolean resizable, boolean closeable) {
        this(parent, title, resizable, closeable, false);
    }

    public ModalityInternalFrame(JComponent parent, String title, boolean resizable, boolean closeable, boolean maximizable) {
        this(parent, title, resizable, closeable, maximizable, false);
    }

    public ModalityInternalFrame(JComponent parent, String title, boolean resizable, boolean closeable, boolean maximizable, boolean iconifiable) {
        super(title, resizable, closeable, maximizable, iconifiable);
        setDefault(parent);
    }

    private void setDefault(JComponent parent) {
        setParentFrame(parent);
        setFocusTraversalKeysEnabled(false);
        if (parent != null && parent instanceof ModalityInternalFrame) {
            ((ModalityInternalFrame) parent).setChildFrame(ModalityInternalFrame.this);
        }

        ModalityInternalGlassPane glassPane = new ModalityInternalGlassPane(this);
        setGlassPane(glassPane);

        addFrameListener();

        addFrameVetoListener();
        init();
    }

    @Override
    public void setTitle(String title) {
        super.setTitle(title);
        super.updateUI();
    }

    @Override
    public void setClosable(boolean value) {
        super.setClosable(value);
        super.updateUI();
    }

    private void setParentFrame(JComponent parent) {
        desktopPane = JOptionPane.getDesktopPaneForComponent(parent);
        this.parent = parent == null ? JOptionPane.getDesktopPaneForComponent(parent) : parent; // default to desktop if no parent given
    }

    public JComponent getParentFrame() {
        return parent;
    }

    public void setChildFrame(ModalityInternalFrame childFrame) {
        this.childFrame = childFrame;
    }

    public ModalityInternalFrame getChildFrame() {
        return childFrame;
    }

    public boolean hasChildFrame() {
        return (childFrame != null);
    }

    protected void addFrameVetoListener() {
        addVetoableChangeListener((PropertyChangeEvent evt) -> {
            if (evt.getPropertyName().equals(JInternalFrame.IS_SELECTED_PROPERTY)
                    && evt.getNewValue().equals(Boolean.TRUE)) {
                if (hasChildFrame()) {
                    childFrame.setSelected(true);
                    if (childFrame.isIcon()) {
                        childFrame.setIcon(false);
                    }
                }
            }
        });
    }

    protected void addFrameListener() {
        addInternalFrameListener(new InternalFrameAdapter() {

            @Override
            public void internalFrameActivated(InternalFrameEvent e) {
                if (hasChildFrame() == true) {
                    getGlassPane().setVisible(true);
                    grabFocus();
                } else {
                    getGlassPane().setVisible(false);
                }
            }

            @Override
            public void internalFrameDeactivated(InternalFrameEvent e) {
                if (hasChildFrame() == true) {
                    getGlassPane().setVisible(true);
                    grabFocus();
                } else {
                    getGlassPane().setVisible(false);
                }
            }

            @Override
            public void internalFrameOpened(InternalFrameEvent e) {
                getGlassPane().setVisible(false);
            }

            @Override
            public void internalFrameClosing(InternalFrameEvent e) {
                if (parent != null && parent instanceof ModalityInternalFrame) {
                    ((ModalityInternalFrame) parent).childClosing();
                }
            }
        });
    }

    @Override
    public void setVisible(boolean value) {
        super.setVisible(value);
        if (value == false && parent != null && parent instanceof ModalityInternalFrame) {
            ((ModalityInternalFrame) parent).childClosing();
        }
    }

    protected void childClosing() {
        setClosable(wasCloseable);
        getGlassPane().setVisible(false);
        if (focusOwner != null) {
            java.awt.EventQueue.invokeLater(() -> {
                try {
                    moveToFront();
                    setSelected(true);
                    focusOwner.grabFocus();
                    focusOwner.requestFocusInWindow();
                } catch (PropertyVetoException ex) {
                    System.out.println(ex);
                }
            });
            focusOwner.grabFocus();
        }
        setChildFrame(null);
    }

    protected void childOpening() {
        wasCloseable = isClosable();
        setClosable(false);
        focusOwner = (JComponent) getFocusOwner();
        grabFocus();
        getGlassPane().setVisible(true);
    }

    @Override
    public void show() {
        if (parent != null && parent instanceof ModalityInternalFrame) {
            ((ModalityInternalFrame) parent).childOpening();
        }
        calculateBounds();
        super.show();
    }

    private void init() {
        addFocusListener(new FocusAdapter() {
            @Override
            public void focusLost(FocusEvent evt) {
                if (childFrame != null) {
                    ((ModalityInternalFrame) childFrame).moveToFront();
                }
            }

            @Override
            public void focusGained(FocusEvent evt) {
                if (childFrame != null) {
                    ((ModalityInternalFrame) childFrame).moveToFront();
                }
            }
        });

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGap(0, 394, Short.MAX_VALUE));
        layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGap(0, 274, Short.MAX_VALUE));
        pack();
    }

    public void calculateBounds() {
        Dimension frameSize = getPreferredSize();
        Dimension parentSize = new Dimension();
        Dimension rootSize = new Dimension();
        Point frameCoord = new Point();

        if (desktopPane != null) {
            rootSize = desktopPane.getSize();
            frameCoord = SwingUtilities.convertPoint(parent, 0, 0, desktopPane);
            parentSize = parent.getSize();
        }

        int x = (parentSize.width - frameSize.width) / 2 + frameCoord.x;
        int y = (parentSize.height - frameSize.height) / 2 + frameCoord.y;

        int ovrx = x + frameSize.width - rootSize.width;
        int ovry = y + frameSize.height - rootSize.height;
        x = Math.max((ovrx > 0 ? x - ovrx : x), 0);
        y = Math.max((ovry > 0 ? y - ovry : y), 0);
        setBounds(x, y, frameSize.width, frameSize.height);
    }

    class ModalityInternalGlassPane extends JComponent {

        private static final long serialVersionUID = 1L;

        private final ModalityInternalFrame modalFrame;

        public ModalityInternalGlassPane(ModalityInternalFrame frame) {
            modalFrame = frame;
            init();
        }

        private void init() {
            addMouseListener(new MouseAdapter() {

                @Override
                public void mouseClicked(MouseEvent evt) {
                    if (modalFrame.isSelected() == false) {
                        try {
                            modalFrame.setSelected(true);
                            if (modalFrame.hasChildFrame() == false) {
                                setVisible(false);
                            }
                        } catch (PropertyVetoException ex) {
                            System.out.println(ex);
                        }
                    }
                }
            });
        }

        @Override
        public void paint(Graphics g) {
            super.paint(g);
            g.setColor(new Color(255, 255, 255, 100));
            g.fillRect(0, 0, getWidth(), getHeight());
        }
    }
}`

**Comment by mgarin** [comment]
Well, it all makes sense now - custom WebLaF tooltips are currently being displayed on a `WebGlassPane` which is created the moment first tooltip display is requested. If you replace the glass pane with a different implementation you won't be able to display any tooltips at all. 

If you would remove all the code that hides/changes the glass pane from your example - tooltips will start to function once again.

I wouldn't call your internal frame modality solution the best, but WebLaF way of displaying tooltips is not better at all. I will surely be changing tooltips to function on layered pane instead of the glass pane, but that might not be included in the v1.2.9 release as the scope of the changes for it is already gigantic.

As one of the possible solutions (for now) I could suggest moving your "modality" layer to the layered pane instead of replacing the glass pane. To do that you will only need to add a few listeners which will update the size of that layer on internal frame size changes and, obviously, move the layer to some high level (200 or 300+) on the layered pane instead of the glass pane.

**Comment by kandrakah** [comment]
I will check a better way to implement the modal (including checking your suggestion). Anyway, thank you for your attention.

**Comment by mgarin** [comment]
No problem, hopefully it would work out well with the other implementation.
Also, you can track issue #63 which will be updated along with the tooltip changes in v1.3.0.
