### ISSUE TITLE
Add strict EventDispatchThread usage check setting

### ISSUE THREAD

**Issue by mgarin** [mgarin/weblaf#414]
There are multiple issues that could appear in your Swing application when working with UI outside of the EventDispatchThread and unlike Java FX - Swing doesn't have any strict thread checks of its own and doesn't provide any tools to add any.

This non-strict mode might seem convenient or even sound as a feature at first - you can let a few label updates slip out of EDT here and there just to shorten your code - but becomes a huge headache on late stage of application development when you're stuck with some unknown stack traces coming out of nowhere.

This is one of the reasons I want to provide such check within WebLaF so you can enable it and ensure your application does everything right or find out where it doesn't. By default it will, of course, be switched off.

This is how it will be enabled:

``` java
WebLookAndFeel.setEnforceEventDispatchThread ( true );
```

You will also be able to modify this setting at any point in runtime.

**Comment by kovadam69** [comment]
This is a great feature! Thank you!

**Comment by mgarin** [comment]
This have been added in the latest `styling` branch builds, you can find those on the site and in maven:
http://weblookandfeel.com/downloads/styling/
https://oss.sonatype.org/content/repositories/snapshots/com/weblookandfeel/

**Comment by mgarin** [comment]
Behavior of this feature can now be adjusted ( 1eaaeaa ).
There is also a wiki article available with full information: 
https://github.com/mgarin/weblaf/wiki/Forced-EDT-usage
