### ISSUE TITLE
WebSplitPane divider background color

### ISSUE THREAD

**Issue by nmagre** [mgarin/weblaf#418]
I don't know if it's a bug or a choice but divider does not have the same background color (it's "white" instead of "gray")

![divider](https://cloud.githubusercontent.com/assets/5362098/19964805/2869a232-a1c4-11e6-87d9-7201dbf83712.png)

Weblaf : 1.2.9-20161031.190504-73
Java: openjdk version 1.8.0_102
OS: Linux

**Comment by mgarin** [comment]
This is not a bug, it is simply split pane default style. And it is also the way split pane component itself works in this specific case. Here is a small code sample:
```java
public class SplitPaneSample
{
    public static void main ( String[] args )
    {
        WebLookAndFeel.install ();

        final JButton left = new JButton ( "Left side" );
        final JButton right = new JButton ( "Right side" );
        final JSplitPane splitPane = new JSplitPane ( JSplitPane.HORIZONTAL_SPLIT, left, right );
        splitPane.setResizeWeight ( 0.5d );
        splitPane.setPreferredSize ( new Dimension ( 500, 200 ) );

        TestFrame.show ( splitPane, 25 ).setContentBackground ( new Color ( 237, 237, 237 ) );
    }
}
```
Result, as you shown, will be the white background:
![image](https://cloud.githubusercontent.com/assets/2361389/19976622/855dde80-a201-11e6-9a38-2811f68b7952.png)

The whole area of the split pane has white background, including divider as it doesn't have its own color. You will only see separate hovering gray line if you try dragging divider with proxy layout on ( it is enabled by default ), for the continuous layout on ( `splitPane.setContinuousLayout(...)` ) there will be no separate representation of the divider. It was my old initial concept of how split pane should look.

If you want to adjust background color - right now you can do that by directly changing background color of the split pane:
```java
splitPane.setBackground ( new Color ( 237, 237, 237 ) );
```
Or by customizing background in split pane component XML style in one:
```java
    <style type="splitpane" id="my-split">
        <component>
            <background>237,237,237</background>
        </component>
    </style>
```
or another way:
```java
    <style type="splitpane" id="my-split">
        <painter>
            <decorations>
                <decoration>
                    <WebShape round="0" />
                    <ColorBackground color="237,237,237" />
                </decoration>
            </decorations>
        </painter>
    </style>
```
Difference between these approaches is quite difficult to describe, I'd recommend reading [this article](https://github.com/mgarin/weblaf/wiki/Styling-introduction) about styling system first. Shortly - the third approach is recommended for better compatibility with future versions, but result for all of the three options will be the same right now:
![image](https://cloud.githubusercontent.com/assets/2361389/19977522/ec55eeb8-a204-11e6-8eaa-a5689d1a7594.png)

---

That all being said - split pane still requires some work and I will be doing some adjustments before the final v1.2.9 update release. So I'll keep this issue open for now and will post more updates here when changes are available in `styling` branch and fresh builds :)

**Comment by nmagre** [comment]
Thanks for the explanation, but I'm not sure to understand why I need to set it.
In previous WebLaf version 1.2.8- , there was no need to set background,... it was already with the "good" color, which is why I reported it. In 1.2.9 I need to find which color your are using and set it, it's not a big deal but less convenient than before.

**Comment by mgarin** [comment]
I've been adjusting quite a few things with `JSplitPane` since this bug got last update and today I've also pushed a major update for it. It is now fully supported by styling system and its visuals can be easily adjusted through styles.

And yes, on top of that default style should go back to gray as it was a bad decision to make it white by default.
