### ISSUE TITLE
Questions: How to change the foreground/font for disabled buttons

### ISSUE THREAD

**Issue by Mark-Shorcan** [mgarin/weblaf#479]
Hi,
I am using the weblaf 1.25
I want to modify the font and foreground for disabled buttons, I tried using UIManger and set text with html, but none of them works.
Would you let me know if there is a way to do it ?
Thank you very much

**Comment by mgarin** [comment]
Unfortunately changing font for specific component state (like disabled in your case) on a global scale for a specific component is not posible as all components use pretty much the same font for any state. 

You can see all fonts used in v1.25 in `WebLookAndFeel` class:
https://github.com/mgarin/weblaf/blob/v1.25/src/com/alee/laf/WebLookAndFeel.java#L204

You can change those fonts before installing L&F to globally change component fonts, but that will affect all of their states. 

If you want to make a specific font for specific state you will have to extend from the component (`JButton` or `WebButton` in your case) and provide appropriate updates on state changes within that component. There is no easier way to do that yet, even in the latest v1.2.9 versions. It will become possible after improvements coming with the `FontManager`: #331 (should be coming in v1.3.0 update)

Similar goes for the foreground in v1.25 update - you cannot provide disabled foreground. You can only configure some of the component style settings in older versions through the style classes like `WebButtonStyle`, but they do lack a lot of things you might want to customize.

In the newest version (v1.2.9 from `styling` branch) you can specify separate foregrounds in the style XML for the default button style to change it as foreground is simply one of the options for the button text state:
```xml
    <style type="button" padding="2,4,2,4">
        <painter>
            <decorations>
                <decoration>
                    <WebShape round="3" />
                    <WebShadow type="outer" width="2" />
                    <LineBorder color="170,170,170" />
                    <GradientBackground>
                        <color>white</color>
                        <color>223,223,223</color>
                    </GradientBackground>
                    <ButtonLayout>
                        <ButtonIcon constraints="icon" />
                        <ButtonText constraints="text" color="black" />
                    </ButtonLayout>
                </decoration>
                <decoration states="focused">
                    <LineBorder color="85,130,190" />
                </decoration>
                <decoration states="pressed">
                    <WebShadow type="outer" opacity="0" />
                    <WebShadow type="inner" width="6" />
                    <ColorBackground color="210,210,210" />
                </decoration>
                <decoration states="disabled">
                    <WebShadow type="outer" opacity="0" />
                    <LineBorder color="lightGray" />
                    <ButtonLayout>
                        <ButtonText color="120,120,120" />
                    </ButtonLayout>
                </decoration>
            </decorations>
        </painter>
    </style>
```
This is the default style for the button from [`button.xml`](https://github.com/mgarin/weblaf/blob/styling/modules/ui/src/com/alee/skin/web/resources/button.xml) which can be modified to adjust default button look and feel. For you case - you can simply specify a different color for `<ButtonText>` in `disabled` state.

About `UIManager` - initially I tried to preserve all settings provided by it. But customizing UI through the Swing `UIManager` brings quite a few issues:

- There are not enough settings available
- Existing settings are not visible and quite often require you to go through the code to find them
- It is quite inconvenient to configure complex UI through the plain properties in `UIManager`
- Changing any of the settings doesn't update existing UI in most cases

That is why in later iterations of the library I went further away from primitive tools provided by Swing and shifted all UI configurations into custom skins/styles provided by WebLaF. That is why most settings provided by `UIManager` are simply ignored and not used.

**Comment by mgarin** [comment]
I'll be closing this issue, but feel free to reopen it or create a new one if you have any more questions/problems.
