### ISSUE TITLE
How do I change the title bar colour of WebFrame for Windows 10?

### ISSUE THREAD

**Issue by MidhunVarghese** [mgarin/weblaf#484]
Here is the webframe which i want to modify.
[https://imgur.com/USuxb8W](https://imgur.com/USuxb8W)

I want to change the Title Bar background colour. I tried searching but i couldnt find any option. Any possibilities that i can achieve this?

**Comment by mgarin** [comment]
Unfortunately the decoration you're looking at is a native Windows 10 decoration, you are not able to modify it anyhow from within your Java application. It only relies on the Windows 10 appearance settings and will always be the same for all windows in the system.

So as long as you want to keep the native decoration - there is no way to change the title background.

**Comment by mgarin** [comment]
I'll be closing this question, but here is a related wiki article that might help you to understand how window decorations work a bit better:
https://github.com/mgarin/weblaf/wiki/Window-decoration
