### ISSUE TITLE
how to run demo for styling branch 

### ISSUE THREAD

**Issue by mokun** [mgarin/weblaf#487]
Hi,

weblaf is a great piece of work! 

Where can I find the demo jar showcasing the latest features ?

I go to https://oss.sonatype.org/content/repositories/snapshots/com/weblookandfeel/weblaf-demo/ and download the latest demo jar from the styling branch but it doesn't run. Surely its size is only 583KB.

I still have the old demo jar which is 10.5MB

Thanks much

**Comment by mgarin** [comment]
Demo JAR file that is available here:
https://oss.sonatype.org/content/repositories/snapshots/com/weblookandfeel/weblaf-demo/
is just a standalone demo module, it requires all other modules and dependencies to run.

The right way to do it is to download sources from here:
https://github.com/mgarin/weblaf/tree/styling
and use included ANT script or Maven project to build all artifacts.

But you can also run it from snapshot artifacts.
For that you need to download two other modules:
https://oss.sonatype.org/content/repositories/snapshots/com/weblookandfeel/weblaf-core/
https://oss.sonatype.org/content/repositories/snapshots/com/weblookandfeel/weblaf-ui/
all dependencies:
https://github.com/mgarin/weblaf/tree/styling/lib
and put them together in one folder.
Module names shouldn't include Maven version but only `SNAPSHOT` in their name:
`weblaf-core-1.2.9-SNAPSHOT.jar`
`weblaf-ui-1.2.9-SNAPSHOT.jar`
That should allow you to run demo JAR.

**Comment by mgarin** [comment]
Fully working artifacts will be available in future, upon the final release of the `styling` branch library version.

**Comment by mokun** [comment]
ok. I just did exactly as told. it still can't run.

is filters-2.0.235.jar from the lib missing ?

**Comment by mokun** [comment]
just notice that the dependencies that I downloaded from your site 
https://github.com/mgarin/weblaf/tree/styling/lib have the wrong file size. 

For instance, svg-salamander-1.0.jar that I've been playing around is 300kB but the one posted in your github site is 57kB only. 

No way all 9 jars have the same size of 57kB or 58kB.

**Comment by mgarin** [comment]
I tried it yesterday and tried it now - all libs located here:
https://github.com/mgarin/weblaf/tree/styling/lib
have proper size and aren't corrupted.

The one you mentioned - `svg-salamander-1.0.jar` - has ~300kb size, not 57, so it looks like your download was interrupted or corrupted somehow. Try re-downloading it.

And you can actually even see the size on the file page:
https://github.com/mgarin/weblaf/blob/styling/lib/svg-salamander-1.0.jar
its exactly 300 KB for this one.

**Comment by mgarin** [comment]
If it still doesn't work for you - you can try downloading the whole project at once and then extract libraries from it (it's not too big). 

If that doesn't work either - you can also get respective versions of the libraries straight from maven central: http://search.maven.org/

**Comment by mgarin** [comment]
I've updated this issue slightly and I will be adding a small guide on how exactly (step by step) you can run demo application from release version and from snapshot repository artifacts as it might actually be quite hard without knowing all of the specifics.

**Comment by mokun** [comment]
Thanks! I have no idea what happened as to why github or the chrome browser would trim all download to 57kB on that day.  I didn't have time to isolate the cause on that day. At least now the downloads works normally.

**Comment by mgarin** [comment]
Thanks for update and I'm glad it worked out for you :)
