### ISSUE TITLE
issue with javax.swing.Box

### ISSUE THREAD

**Issue by mokun** [mgarin/weblaf#505]
Hi, 

When I run my app,

```
	public ExplorationCustomInfoPanel() {
		// Use JPanel constructor
		super();

		setLayout(new BorderLayout());

		// Create the main scroll panel.
		WebScrollPane mainScrollPane = new WebScrollPane();
		add(mainScrollPane, BorderLayout.NORTH);

		// Create main panel.
		mainPane = Box.createVerticalBox();
		mainScrollPane.setViewportView(mainPane);

		sitePanes = new HashMap<String, ExplorationSitePanel>(5);
	}
```

I encountered the following at `mainPane = Box.createVerticalBox()`

```
Exception in thread "AWT-EventQueue-0" com.alee.managers.style.StyleException: Unable to retrieve component UI: javax.swing.Box[,0,0,0x0,invalid,layout=javax.swing.BoxLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=0,maximumSize=,minimumSize=,preferredSize=]
```

> Note: this occurs only in Java 1.8_191. When I run my app in Java 10.0.2, it reports no issue with the swing Box.

I guess I had similar issue before with integrating weblaf and `javax.swing.Box`.

What should I do ?
Thanks!

**Comment by mgarin** [comment]
It looks like there is an issue with adding any kinds of components that do not have UI into WebLaF's scroll pane - apparently that have never ever been a case before (actually shocking). I will fix it shortly and push a new snapshot build based on `styling` branch code.

P.S. Sorry for the veeeeeery slow response, last week before long holidays here and it's a bit crazy.

**Comment by mgarin** [comment]
New `styling` branch snapshot with the fix for this issue is out, you can try it out.

I will also make an extra pass through the code to see similar UI use cases and fix them a bit later (saw a few already), although everything should function properly even without those additional changes in the current snapshot version.

**Comment by mokun** [comment]
I can see styling branch at https://github.com/mgarin/weblaf/tree/styling.

How do I switch to using styling snapshot in maven ?

Currently, my app uses this : 

```
        <dependency>
            <groupId>com.weblookandfeel</groupId>
            <artifactId>weblaf-ui</artifactId>         
            <version>1.2.9-SNAPSHOT</version>
        </dependency>		
		<dependency>
		    <groupId>com.weblookandfeel</groupId>
		    <artifactId>weblaf-core</artifactId>    
            <version>1.2.9-SNAPSHOT</version>
	</dependency>
```

**Comment by mgarin** [comment]
That is already the snapshot version you need :)

Although you probably also need to have repository specified, here is what I usually use whenever I attach WebLaF to any of my Maven projects:
```xml
    <dependencies>
        <dependency>
            <groupId>com.weblookandfeel</groupId>
            <artifactId>weblaf-ui</artifactId>
            <version>1.2.9-SNAPSHOT</version>
        </dependency>
    </dependencies>

    <repositories>
        <repository>
            <id>sonatype-snapshot-rep</id>
            <name>Sonatype snapshot repository</name>
            <url>https://oss.sonatype.org/content/repositories/snapshots</url>
        </repository>
    </repositories>
```

You just need to make sure that whatever IDE you're using is set to always update the snapshot artifacts, for instance in IntelliJ Idea you can find that setting here:

![image](https://user-images.githubusercontent.com/2361389/50453790-2b4ed400-0954-11e9-84ee-34abffe644d1.png)

**Comment by mokun** [comment]
oic. Thx!

**Comment by mgarin** [comment]
Although I wouldn't recommend downloading them manually (especially snapshot version) - using the proper maven dependency is surely times better :)
