### ISSUE TITLE
WebAccordion selection listener issue

### ISSUE THREAD

**Issue by particleflow16** [mgarin/weblaf#506]
WebAccordion#addAccordionListener rarely recieves "selectionChanged()" notification when selection change occurs due to removal of current selected pane

**Comment by mgarin** [comment]
There are multiple issues with listeners and component overall. I have already completed collapsible pane rework locally and accordion rework will also be done before those changes are committed - this issue will be fixed along with the rework.

**Comment by mgarin** [comment]
With v1.2.9 update `WebAccordion` have been completely reworked.

Regarding the specific issue noted here - first of all there is no selection listener for accordion anymore, there is an `AccordionListener` that allows tracking expansion and collapse of each pane. It will not fire whenever pane is added or removed, but instead only when pane is expanded or collapsed, which can of course happen upon it's addition to the accordion depending on accordion settings.

I don't think that it is reasonable to fire the event at any other occasion. It is surely better to listen for panes addition & removal through standard `ContainerListener`.

Selection listener might appear later on for accordion if it will be useful, it will basically track which of the accordion panes is currently "selected" (basically focused) out of expanded ones.
