### ISSUE TITLE
[DEBUG] Could not find metadata com.weblookandfeel:weblaf-ui:1.2.9-SNAPSHOT/maven-metadata.xml in local (/home/shirish/.m2/repository)

### ISSUE THREAD

**Issue by shirishag75** [mgarin/weblaf#507]
Hi all, 

Please let me know if any more info. is needed.

**Comment by mgarin** [comment]
I'm not sure under what circumstances you get that issue, can you elaborate?
Also I checked availability of `styling` branch snapshot builds and everything seem to be fine.

**Comment by mgarin** [comment]
Just in case, this is how I include latest snapshot build in my maven projects:
```xml
    <dependencies>
        <dependency>
            <groupId>com.weblookandfeel</groupId>
            <artifactId>weblaf-ui</artifactId>
            <version>1.2.9-SNAPSHOT</version>
        </dependency>
    </dependencies>

    <repositories>
        <repository>
            <id>sonatype-snapshot-rep</id>
            <name>Sonatype snapshot repository</name>
            <url>https://oss.sonatype.org/content/repositories/snapshots</url>
        </repository>
    </repositories>
```
This should be enough to get access to all WebLaF features.

**Comment by shirishag75** [comment]
we are also using the same snapshot in https://github.com/mars-sim/mars-sim/blob/master/mars-sim-ui/pom.xml

**Comment by mgarin** [comment]
So, is it working for you now?
Also there haven't been any recent commits (last ones were made in December).

**Comment by mgarin** [comment]
I'll assume the problem was solved, so i'll close this issue.
Feel free to reopen if you encounter it again.
