### ISSUE TITLE
Finding UIManager key related to tree handles

### ISSUE THREAD

**Issue by mvrozanti** [mgarin/weblaf#510]
Hi there! Me again!

This time, I'm trying to find out how to customize certain UI elements. I've noticed that some `UIManager.put` calls have now been ignored (once `WebLookAndFeel` is installed).

The ones that I have managed to verify are:
```
		UIManager.put("Tree.collapsedIcon", closedIcon);
		UIManager.put("Tree.expandedIcon", openIcon);
		UIManager.put("Tree.closedIcon", closedIcon);
		UIManager.put("Tree.openIcon", openIcon);
```

With Swing, I get the following renderization:
![image](https://user-images.githubusercontent.com/11381662/57163075-85f6b180-6dc6-11e9-8adf-aec77aedd95d.png)

With WebLAF, I get this:

![image](https://user-images.githubusercontent.com/11381662/57163121-a45cad00-6dc6-11e9-8692-61c66080153c.png)

Is there a quick workaround __without__ using `Skin`s and `Style`s?

Thanks!

**Comment by mgarin** [comment]
By the looks of the screenshot - you are using older version of the library, meaning it probably still had most icons stored in static fields for each particular component, in this case - for the tree. If that is the case - you can simply reassign `WebTreeUI.EXPAND_ICON` and `WebTreeUI.COLLAPSE_ICON` field values (and their disabled counterparts if needed) located in [WebTreeUI](https://github.com/mgarin/weblaf/blob/master/modules/ui/src/com/alee/laf/tree/WebTreeUI.java) class.

Once you will be moving to newer versions (which I highly recommend as those are more stable and polished) - you will need to work with WebLaF's styling system to modify them. To be more precise - you will need to provide a custom `IconSet` into `IconManager` which will contain replacement for default icons used in the tree. Each `IconSet` is basically a simple mapping of icon identifiers to icons, so for the tree you will need to provide icons for next identifiers: `square-plus`, `square-plus-disabled`, `square-minus` and `square-minus-disabled`.

**Comment by mvrozanti** [comment]
Thanks! This works perfectly

**Comment by mvrozanti** [comment]
@mgarin I've checked the version, I got 1.29 at the moment

**Comment by mgarin** [comment]
Yep, that is a stable but quite aged version at this point.

I have been working on a major update for last few years that is available in `styling` [branch](https://github.com/mgarin/weblaf/tree/styling). It includes a lot of fixes, improvements and new component additions to the library. Although builds of this version are only available on [Sonatype snapshot repository](https://oss.sonatype.org/content/repositories/snapshots/com/weblookandfeel/) or can be included in maven projects:
```xml
    <dependencies>
        <dependency>
            <groupId>com.weblookandfeel</groupId>
            <artifactId>weblaf-ui</artifactId>
            <version>1.2.9-SNAPSHOT</version>
        </dependency>
    </dependencies>

    <repositories>
        <repository>
            <id>jcenter</id>
            <name>jcenter-bintray</name>
            <url>http://jcenter.bintray.com</url>
        </repository>
        <repository>
            <id>sonatype-snapshot-rep</id>
            <name>Sonatype snapshot repository</name>
            <url>https://oss.sonatype.org/content/repositories/snapshots</url>
        </repository>
    </repositories>
```
It will be available on the site and in releases section here once it is complete - there are still a few things to be done for full styling support in all components.
