### ISSUE TITLE
CustomSkin class not available

### ISSUE THREAD

**Issue by mokun** [mgarin/weblaf#521]
Hi,

Where can I find the `CustomSkin` class ? 

I'm reading this [styling wiki](https://github.com/mgarin/weblaf/wiki/Styling-introduction) and would like to try out [styling-example.zip](http://weblookandfeel.com/wiki/styling-example.zip).

In my pom.xml, I have

```
        <dependency>
            <groupId>com.weblookandfeel</groupId>
            <artifactId>weblaf-ui</artifactId>        
            <version>1.2.9</version>
        </dependency>	
	<dependency>
	    <groupId>com.weblookandfeel</groupId>
	    <artifactId>weblaf-core</artifactId>       
           <version>1.2.9</version>
	</dependency>
	<dependency>
	    <groupId>com.weblookandfeel</groupId>
	    <artifactId>weblaf-plugin</artifactId>        
            <version>1.2.9</version>
	</dependency>
```

But as I unzip that and look at `Example.java`, my Eclipse have the `CustomSkin` class underlined in red.

```
        final CustomSkin defaultSkin = new CustomSkin ( Example.class, "ExampleSkin.xml" );
        final CustomSkin darkSkin = new CustomSkin ( Example.class, "DarkExampleSkin.xml" );

```

I surmise may be things have changed in the just released 1.2.9 and how do you loading a xml skin these days ? Any example pack ? 

Thanks ahead of time !

**Comment by mgarin** [comment]
As I mentioned on Gitter - `CustomSkin` class have been removed and isn't in the latest version, thanks for finding the issue in the wiki article, i'll be fixing it soon.

To make a custom skin right now you need to use or extend `XmlSkin` and provide the XML resource to it in constructor. Then you need the skin's XML file itself with settings, description, styles etc.

At that point you can just use the instance of `XmlSkin` or your class that extends it in the StyleManager. If you make your own class that extends `XmlSkin` you can simply provide it into `WebLookAndFeel.install ( ... )` and it will create skin instance on its own.

**Comment by mgarin** [comment]
I have updated "Styling introduction" wiki article according to changes in v1.2.9 update, you can read it here: https://github.com/mgarin/weblaf/wiki/Styling-introduction

**Comment by mgarin** [comment]
Just a side note - I've removed the ZIP with old examples and didn't add new one, but you can simply copy-paste two classes & skin XML from the article and it should work.
