### ISSUE TITLE
how to create a round corner "tag" using WebStyledLabel 

### ISSUE THREAD

**Issue by mokun** [mgarin/weblaf#522]
I'm trying to create a bunch of tag labels in a desktop application, much like those label tag label in the issue tracker in any GitHub repo.

See within the red circles in the pic below : 

![vaadin tags](https://user-images.githubusercontent.com/1168584/63075074-2d66a280-bee5-11e9-9982-61b2beac5952.jpg)

![tag labels](https://user-images.githubusercontent.com/1168584/63068807-73ae0880-bec9-11e9-983e-9fe205e50039.jpg)

So I'm trying to follow [wiki](https://github.com/mgarin/weblaf/wiki/How-to-use-WebStyledLabel) on WebStyledLabel on how to set up the styling by using the curly braces `{` and `}`.

I've tried this but didn't work : 
```
WebStyledLabel label = new WebStyledLabel("{None:c(white)} {bg(gray)}");
label.setText("testing");
```
> Note that I have to define the text of the label at runtime.

How do you turn the background of the WebStyledLabel instance to grey and use the white font color all in one line ?

Also, is there a way to tweak this tag label to having round corners (instead of having rather sharp 90 degree corners), since the 4 corners of a keyword/tag label is usually round to make it stand out ?

Thanks much !

**Comment by mokun** [comment]
I get the background color partially working now.
 
```
for (String t: topics) {
	WebStyledLabel label = new WebStyledLabel("{None:b;c(white);background(darkgray)}");
	label.setStyleId(StyleId.styledlabelShadow);
	label.setText(t);			
	topicPanel.add(label);
}	
```

However, I cannot use the string value of the label at runtime. By calling setText(), the font color and background color are gone. `styledlabelShadow` still works.

Also, I wonder if I can modify the label to have round corners.

**Comment by mgarin** [comment]
`WebStyledLabel` syntax is not meant to style the whole component, but only to style the text or its parts, basically what you would normally use HTML in `JLabel` for. The difference is - HTML rendering is very slow, while `WebStyledLabel` syntax rendering is extremely fast and on par with normal text rendering, so it is way better for any List/Tree/Table renderers and even for general use as well.

To get the decoration you want around the component you can either use basic `StyleId.labelTag` or `StyleId.styledlabelTag` style - it is probably the closest to what you want:
```java
public class Example
{
    public static void main ( final String[] args )
    {
        SwingUtilities.invokeLater ( new Runnable ()
        {
            @Override
            public void run ()
            {
                WebLookAndFeel.install ();
                TestFrame.show (
                        new FlowLayout (), 20,
                        new WebLabel ( StyleId.labelTag, "Simple label" ),
                        new WebStyledLabel ( StyleId.styledlabelTag, "Styled label" ),
                        new WebStyledLabel ( StyleId.styledlabelTag, "{Sample:b} {label:i}" ),
                        new WebStyledLabel ( StyleId.styledlabelTag, "{Sample label:b;c(red)}" )
                ).setContentBackground ( Color.WHITE );
            }
        } );
    }
}
```

![image](https://user-images.githubusercontent.com/2361389/63082609-5459be80-bf4f-11e9-8a1e-73287fcd215f.png)

Or write your own style for the `label`, `styledlabel` or any other component. Here is, for instance, the XML style of the `StyleId.styledlabelTag` basic style:
```xml
    <!-- Label with tag decoration -->
    <style type="styledlabel" id="tag" padding="2,5,2,5">
        <painter>
            <decorations>
                <decoration>
                    <WebShape round="3" />
                    <LineBorder color="185,185,185" />
                    <ColorBackground color="237,237,237" />
                </decoration>
            </decorations>
        </painter>
    </style>
```
Taken from [styledlabel.xml](https://github.com/mgarin/weblaf/blob/master/modules/ui/src/com/alee/skin/web/resources/styledlabel.xml) from the `WebSkin`.

**Comment by mgarin** [comment]
I also recommend re-checking [Styling introduction](https://github.com/mgarin/weblaf/wiki/Styling-introduction) wiki article - I've updated it just yesterday and it now properly explains how you can create skin and customize component style step-by-step.

**Comment by mgarin** [comment]
I'll be closing this one, but feel free to reopen it or make a new one if you still have some questions or issues.
