### ISSUE TITLE
WebCollapsiblePane click bug

### ISSUE THREAD

**Issue by Husker-hub** [mgarin/weblaf#533]
WebCollapsiblePane click triggered when I press title and release in another point.

![image](https://user-images.githubusercontent.com/31825139/64713491-a4339300-d4c5-11e9-8c6f-854c5a7faca9.png)

**Comment by mgarin** [comment]
I guess it's a tiny thing, but it should indeed function similarly to a button so that actual click is not triggered when you move the mouse cursor out before releasing the mouse. I will add a small fix for that in v1.2.11 update.

**Comment by mgarin** [comment]
I've updated header panel to avoid being triggered if mouse was moved outside of the header bounds.
Change will be available in v1.2.11 update.
