### ISSUE TITLE
WebDockableFrame position

### ISSUE THREAD

**Issue by Husker-hub** [mgarin/weblaf#537]
How can I programmatically set the position of the frame, as shown in screenshot?

I tried to use ```setPosition(CompassDirection.southEast)```  and ```setPosition(CompassDirection.southWest)``` but it throws exception: 
```java 
java.lang.RuntimeException: Unknown element position specified
```

![image](https://user-images.githubusercontent.com/31825139/65159369-a3a67980-da3c-11e9-9dbe-afe40abd1b5f.png)

**Comment by mgarin** [comment]
There is no simple way to configure complex frame positions since it will not be descriptive enough for the dockable pane, so if you want to setup a complex default layout - you'll have to fully define it using the same state that is used to save any `WebDockablePane` state:
```java
final WebDockablePane pane = new WebDockablePane ();

/** ... Define your frames here ... **/

final DockableListContainer state = new DockableListContainer ( Orientation.vertical );

final DockableFrameElement northElement = new DockableFrameElement ( northFrame );
northElement.setSize ( new Dimension ( 500, 200 ) );
state.add ( 0, northElement );

final DockableListContainer centerContainer = new DockableListContainer ( Orientation.horizontal );
centerContainer.add ( 0, new DockableFrameElement ( westFrame ) );
centerContainer.add ( 1, new DockableContentElement () );
centerContainer.add ( 2, new DockableFrameElement ( eastFrame ) );
state.add ( 1, centerContainer );

final DockableListContainer southContainer = new DockableListContainer ( Orientation.horizontal );
centerContainer.add ( 0, new DockableFrameElement ( southWestFrame ) );
centerContainer.add ( 0, new DockableFrameElement ( southEastFrame ) );

pane.setState ( state );
```

The structure of `WebDockablePane` is fairly simple - it uses horizontal and vertical groups (defined by `DockableListContainer` in the state) to group up the contents in any way.

Here is a simple breakdown of the layout you've shown on your screenshot:
![image](https://user-images.githubusercontent.com/2361389/65226062-e5800000-dace-11e9-849d-cc53fbf3730a.png)

#1 - is the `DockableListContainer` I placed under `state` variable in the code example above
#2 - is the `DockableListContainer` I placed under `centerContainer` variable
#3 - is the `DockableListContainer` I placed under `southContainer` variable

There is no depth limitation, you can insert as many `DockableListContainer` into each other as your layout needs. The only thing that is required is to have one `DockableContentElement` (not more and not less) which will define where content area is placed.

**Comment by mgarin** [comment]
I might improve the basic positioning possibilities later on - maybe include simple position options like the ones you tried (like `CompassDirection.southEast`) - but for now I didn't want to overcomplicate the base implementation until it is polished enough.

A few updates later I will be revisiting `WebDockablePane` to add grouping support (see #397) and probably some other features including the additional positioning options.

**Comment by mgarin** [comment]
I've added a separate issue for future improvements to initial positioning of frames: #544

**Comment by mgarin** [comment]
I'll be closing this issue as the question should be answered.
Feel free to reopen if you're still experiencing issues.

**Comment by Husker-hub** [comment]
I tried your solution, but nothing is displayed except content

![image](https://user-images.githubusercontent.com/31825139/65884244-2b777680-e3a1-11e9-900a-0d31fcb212df.png)


```java
WebDockablePane dockablePane = new WebDockablePane();
dockablePane.setSidebarVisibility(SidebarVisibility.anyMinimized);
dockablePane.setContent(new DrawingPanel());

dockablePane.setState(new DockableListContainer(Orientation.vertical){{

    // Top
    DockableFrameElement northElement = new DockableFrameElement(Panel_Projects);
    add(0, northElement);

    // Center
    DockableListContainer centerContainer = new DockableListContainer(Orientation.horizontal);
    centerContainer.add(0, new DockableFrameElement(Panel_Parameters));
    centerContainer.add(1, new DockableContentElement());
    centerContainer.add(2, new DockableFrameElement(Panel_TexturesList));
    add(1, centerContainer);

    // Bottom
    DockableListContainer southContainer = new DockableListContainer(Orientation.horizontal);
    southContainer.add(0, new DockableFrameElement(Panel_Resources));
    southContainer.add(1, new DockableFrameElement(Panel_Project_Resources));
    add(2, southContainer);
}});
add(dockablePane);
```

**Comment by mgarin** [comment]
I forgot to mention that in original response - you still need to add your `WebDockableFrame`s into `WebDockablePane` before applying the state, state itself just represents the layout of the elements within `WebDockablePane`. Here is a full example:
```java
public class DockTest
{
    public static void main ( final String[] args )
    {
        SwingTest.run ( new Runnable ()
        {
            @Override
            public void run ()
            {
                final WebDockablePane dockablePane = new WebDockablePane ();
                dockablePane.setSidebarVisibility ( SidebarVisibility.anyMinimized );
                dockablePane.setPreferredSize ( 800, 600 );

                final JPanel content = new JPanel ();
                content.setBorder ( BorderFactory.createLineBorder ( Color.RED, 1 ) );
                dockablePane.setContent ( content );

                final WebDockableFrame north = new WebDockableFrame ( "north", "North" );
                north.setPreferredSize ( 200, 150 );
                dockablePane.addFrame ( north );

                final WebDockableFrame west = new WebDockableFrame ( "west", "West" );
                west.setPreferredSize ( 200, 100 );
                dockablePane.addFrame ( west );

                final WebDockableFrame east = new WebDockableFrame ( "east", "East" );
                east.setPreferredSize ( 200, 100 );
                dockablePane.addFrame ( east );

                final WebDockableFrame southWest = new WebDockableFrame ( "southWest", "South-West" );
                southWest.setPreferredSize ( 200, 100 );
                dockablePane.addFrame ( southWest );

                final WebDockableFrame southEast = new WebDockableFrame ( "southEast", "South-East" );
                southEast.setPreferredSize ( 200, 100 );
                dockablePane.addFrame ( southEast );

                dockablePane.setState ( new DockableListContainer ( Orientation.vertical )
                {{
                    final DockableFrameElement northElement = new DockableFrameElement ( north );
                    add ( 0, northElement );

                    final DockableListContainer centerContainer = new DockableListContainer ( Orientation.horizontal );
                    centerContainer.add ( 0, new DockableFrameElement ( west ) );
                    centerContainer.add ( 1, new DockableContentElement () );
                    centerContainer.add ( 2, new DockableFrameElement ( east ) );
                    add ( 1, centerContainer );

                    final DockableListContainer southContainer = new DockableListContainer ( Orientation.horizontal );
                    southContainer.setSize ( new Dimension ( 200, 150 ) );
                    southContainer.add ( 0, new DockableFrameElement ( southWest ) );
                    southContainer.add ( 1, new DockableFrameElement ( southEast ) );
                    add ( 2, southContainer );
                }} );

                TestFrame.show ( dockablePane );
            }
        } );
    }
}
```

This should work on both v1.2.9 and v1.2.10 updates correctly and give next result:

![image](https://user-images.githubusercontent.com/2361389/65891443-320beb00-e3ad-11e9-8b31-21f85b4093fc.png)

All the sizes are provided above are just for example purpose, dockable should still work without sizes provided - frames will simply use default minimal element size (40x40 px or whatever is set within `WebDockablePane`).

That being said I've found a small issue that would appear on `DockableListContainer` when size is not specified - I've already fixed it locally and will soon push it along with some other improvements I'm bringing to `WebDockablePane`.

I've also added some extra constructors and methods to state elements to simplify their construction in the code. Here is an example of your layout case being defined exclusively through element constructors:
```java
dockablePane.setState ( new DockableListContainer (
        Orientation.vertical,
        new DockableFrameElement ( north, new Dimension ( 200, 150 ) ),
        new DockableListContainer (
                Orientation.horizontal,
                new DockableFrameElement ( west, new Dimension ( 200, 100 ) ),
                new DockableContentElement (),
                new DockableFrameElement ( east, new Dimension ( 200, 100 ) )
        ),
        new DockableListContainer (
                Orientation.horizontal,
                new Dimension ( 200, 150 ),
                new DockableFrameElement ( southWest, new Dimension ( 200, 100 ) ),
                new DockableFrameElement ( southEast, new Dimension ( 200, 100 ) )
        )
) );
```
This will become available in snapshot build shortly and starting from v1.2.11 update.

**Comment by mgarin** [comment]
Just a note - setting a preferred size for `WebDockableFrame` has the same effect when running example above as if you would instead set the same size into the `DockableFrameElement` because it basically grabs the preferred size as the initial by default. 

Setting initial size directly into `DockableFrameElement` and `DockableListContainer` is a more sensible way to setup the state since it only affects initial `WebDockablePane` layouting and nothing else while setting up preferred size might have some other unwanted side-effects.
