### ISSUE TITLE
Dark Theme

### ISSUE THREAD

**Issue by Sciss** [mgarin/weblaf#54]
I am still having this idea that there could be a dark theme. It doesn't have to be a completely different design like futurico. For example, a first straight forward approximation could be to just invert the brightness of all colors. (I have just inverted RGB and rotated the hue afterwards):

![weblafdark](https://f.cloud.github.com/assets/131300/1423970/f2441840-4014-11e3-9a60-a641cc711a68.png)

What do you think? Is this easy to accomplish? A better variant would also make sure gradient orientations are maintained (e.g. if going from lighter to darker top to bottom, it should remain that way)

**Comment by stephram** [comment]
Your screenshot above looks quite good in my opinion. How did you do that? I tried the same thing - inverting the colors I found by calling LookAndFeel.getDefaults(), but it didn't work. Presumably because that's not the correct place to set them for WebLaf.

**Comment by Sciss** [comment]
Just Photoshop/Gimp. It's inverting RGB and then rotating HSB 180 degrees, so blues stay blue etc. It's not perfect, just an approximation of how I imagine it could work.

**Comment by mgarin** [comment]
There are only a few more things missing from dark skin at this point which yet to be supported by the new styling system. As soon as those things are added - I will be closing this issue and dark skin will officially be a fully supported default skin.

**Comment by Endogen** [comment]
Nice one!

**Comment by mgarin** [comment]
Light and Dark themes (`WebSkin` and `DarkSkin`) have been released in v1.2.9 update:
https://github.com/mgarin/weblaf/releases/tag/v1.2.9
More default skins will become available with future updates.
