### ISSUE TITLE
Check box and radio button icon support

### ISSUE THREAD

**Issue by mgarin** [mgarin/weblaf#573]
Right now checkbox and radio buttons (including menu items) can either display a check/radio icon or a custom icon, but not both at the same time. It would be nice to have them both.

To be more specific - changing component `Icon` should not remove or configure the check/radio icon anyhow, but instead add/remove a custom icon besides it.

For menu items this also means that other items in the same menu will have to be properly aligned to check/radio+custom icon width (or ignore it?).

**Comment by Sciss** [comment]
For reference, here is a screenshot showing metal laf with user icon along checkbox (left) and web laf (right). tooltips are shown.
![cbmi-with-icon-compare](https://user-images.githubusercontent.com/131300/67402733-393fa680-f5b1-11e9-8135-a1d6cc677e61.png)

**Comment by mgarin** [comment]
Yep. I re-checked other L&Fs today to see how they handle it in menus and it is mostly handled like in `MetalLookAndFeel` with a few exceptions.

I will most probably do it the same way it is done in `MetalLookAndFeel` - add check/radio icon in front and move icons of all other menu items forward to line up with check/radio menu item custom icons. The implementation is already in place, I'll just need to tune a few things in UI, content layout and painter.

**Comment by mgarin** [comment]
Ok, since I decided to fix this once and for all - I've made a different approach at rendering state icon for `JCheckBoxMenuItem` and `JRadioButtonMenuItem` to avoid `JCheckBox` and `JRadioButton` implementation affecting them anyhow.

First of all, here is the simple example state icons & custom icons:

![image](https://user-images.githubusercontent.com/2361389/67590742-7ef0a080-f764-11e9-944d-41be9c06f256.png)

Here is how it will align with other elements with state icons only:

![image](https://user-images.githubusercontent.com/2361389/67590899-c545ff80-f764-11e9-8e5c-806e49d588d4.png)

And here are some normal menu items on top:

![image](https://user-images.githubusercontent.com/2361389/67590948-e27ace00-f764-11e9-9cab-a4babc5a434b.png)

And here is a small niche case I've also added proper handling for:

![image](https://user-images.githubusercontent.com/2361389/67590995-03432380-f765-11e9-9a9d-2057bb514a48.png)

This is basically the case when all state menu items do not have any custom icon while some other normal menu items are also present (with and without icons). This allows you not to have two ugly columns each of which is half-empty.

Menu will properly align even with differently-sized icons:

![image](https://user-images.githubusercontent.com/2361389/67591132-5d43e900-f765-11e9-95ae-1cbc4bf307b8.png)

And even if you decide to go wild on the style:

![image](https://user-images.githubusercontent.com/2361389/67591187-82385c00-f765-11e9-9281-020d61bd7ecc.png)

And here is the dark example:

![image](https://user-images.githubusercontent.com/2361389/67591371-f115b500-f765-11e9-91c7-e633901a2d17.png)

Alignments, paddings, layout and other settings can be adjusted for menu items in the style, although hopefully default layout and settings handle most cases. You can even disable aligning menu items:

![image](https://user-images.githubusercontent.com/2361389/67591610-7a2cec00-f766-11e9-8896-1c975e6f91db.png)

I'll be pushing these changes shortly, just need to check everything last time.

**Comment by mgarin** [comment]
These changes are now available in `master`.
Snapshot build should also be available soon.
