### ISSUE TITLE
GroupPane content layout

### ISSUE THREAD

**Issue by Husker-hub** [mgarin/weblaf#583]
How can I configure GroupPane as on screenshot? I need to fill free space with the first ```WebButton```. I have not found methods that can change layout. 

![image](https://user-images.githubusercontent.com/31825139/68994895-ef3c9e80-0898-11ea-8580-032eb69adc97.png)

**Comment by mgarin** [comment]
You can use custom constraints for `GroupPane` (it uses `GroupPaneLayout`):
```java
GroupPane pane = new GroupPane ();
pane.add ( new JButton ( "Test" ), GroupPaneConstraints.FILL );
pane.add ( new JButton ( "-" ) );
TestFrame.show ( pane );
```
`GroupPaneConstraints.FILL` is a predefined one, but you can also create custom `GroupPaneConstraints` with custom sizes, you can check it's JavaDoc for more info:
https://github.com/mgarin/weblaf/blob/master/modules/ui/src/com/alee/laf/grouping/GroupPaneConstraints.java#L47
