### ISSUE TITLE
WebDockableFrame tooltip text

### ISSUE THREAD

**Issue by husker-dev** [mgarin/weblaf#601]
I think that the word ```frame``` is redundant here, because even without ```frame``` it is clear to understand which component will be used.

![image](https://user-images.githubusercontent.com/31825139/71480413-f943ac80-2809-11ea-895e-3ca815c8ea16.png)

https://github.com/mgarin/weblaf/blob/fdf096edf9b207e87a80b313671fadc8db1a0b9f/modules/ui/src/com/alee/managers/language/resources/ui-language.xml#L2147-L2234

**Comment by husker-dev** [comment]
Also this word is strange translated in Russian (```фрейм```). Probably better translation would be ```окно```.

**Comment by mgarin** [comment]
I would argue that `окно` is best translation in this case as it mostly refers to `window`/`frame`/`dialog` in case of UI. But I would agree that it is redundant in this case and I've removed it from all translations.
