### ISSUE TITLE
TableLayout library provenance

### ISSUE THREAD

**Issue by apjanke** [mgarin/weblaf#615]
Hi, weblaf folks!

This isn't an issue with WebLaF per se, but I was hoping you could help me with something. I'm trying to establish the licensing and provenance for Daniel Barbalace's TableLayout library, which looks like it's included here in https://github.com/mgarin/weblaf/blob/4faefd1aae173c02dd534e4b708cc0408f4a3667/modules/ui/src/com/alee/extended/layout/TableLayout.java and related files.

Do you have a copy of the original TableLayout distribution archive which includes the license info? Most of the original [clearthought.info](http://www.clearthought.info) site seems to have fallen off the web, and the only download I can find for TableLayout now is <http://www.clearthought.info/sun/products/jfc/tsc/articles/tablelayout/>, which is an older version that doesn't appear to have license info included. I can't find any contact info for the author.

**Comment by mgarin** [comment]
I don't really have original distribution at this point, the only related thing that can be found in the project is the original license text (which is also available in the `TableLayout` class source code):
https://github.com/mgarin/weblaf/blob/master/licenses/tablelayout.txt

I'm also pretty sure that `TableLayout` class source code wasn't coming from the original distribution, but from one of the projects using it.

**Comment by DevCharly** [comment]
Here is a clone of the original TableLayout SVN repo:
https://github.com/JFormDesigner/swing-tablelayout

**Comment by apjanke** [comment]
Thank you both!

Closing this issue as addressed.
