### ISSUE TITLE
Style icon questions

### ISSUE THREAD

**Issue by husker-dev** [mgarin/weblaf#616]
### Icon types
Why are there several icon files in the ```light/icons``` folder? First ```.png``` image that is referenced in the ```.xml``` skin, and another unknown ```.svg``` image.

### Icon size
Why is a .png image using such a small size? If you use them somewhere, then the size is too small
### Example (Spoilers)

![image](https://user-images.githubusercontent.com/31825139/80286891-ccab8d00-8736-11ea-90ff-7ab1b2375864.png)

(A similar question was sent to the mail, but did not receive an answer)

**Comment by mgarin** [comment]
> Why are there several icon files in the light/icons folder? First .png image that is referenced in the .xml skin, and another unknown .svg image.

Those are simply skin icons. PNG is a relic of the past and will be replaced with the SVG version (that is also already there) once I get to upgrade some SVG-related features.

> Why is a .png image using such a small size? If you use them somewhere, then the size is too small

It is simply a 16x16 icon for skin selection combobox that you can, for instance, see in the demo app. And generally these are not intended for any use outside of any kinds of skin selectors.

Icons that can be used within application are defined in the icon set XML files and are mostly using SVG at this point which can be scaled properly.

**Comment by mgarin** [comment]
> (A similar question was sent to the mail, but did not receive an answer)

Sorry, didn't see your e-mail because for whatever reason either Thunderbird or our mail server marked it as a spam and moved to the spam folder which I barely ever check.
