### ISSUE TITLE
Wiki typo

### ISSUE THREAD

**Issue by husker-dev** [mgarin/weblaf#618]
As I understand it should be ```weblaf-core``` instead of ```weblaf-ui```.

https://github.com/mgarin/weblaf/wiki/How-to-use-WebLaF#weblaf-core-1

![image](https://user-images.githubusercontent.com/31825139/80306825-5c504a80-87ce-11ea-9a7d-2e6e00428e8e.png)

**Comment by mgarin** [comment]
Yep, that's certainly a bad copy-paste :)
Fixed it in the article.
