### ISSUE TITLE
How can I set gradient background colors separately to each windows title bar control buttons?

### ISSUE THREAD

**Issue by UltimateYZ** [mgarin/weblaf#632]
Hi Mgarin,

I'm having some problems to set gradient colour background separately to buttons from id "control", XML file (The same XML file with instructions to paint and decorate the title bar). Is there a simple I way to set them separately?

**Comment by mgarin** [comment]
For button background specifically - style like this:
```xml
    <style type="button" id="control">
        <painter>
            <decorations>
                <decoration>
                    <GradientBackground>
                        <color>111,115,117</color>
                        <color>77,81,83</color>
                    </GradientBackground>
                </decoration>
            </decorations>
        </painter>
    </style>
```
should be enough to adjust the default gradient background. You can change gradient colors, direction or replace it with any other background implementation.

Note that pressed state in [default style](https://github.com/mgarin/weblaf/blob/master/modules/ui/src/com/alee/skin/dark/resources/button.xml) has different (single-colored) background implementation that would need adjustment as well if you want to change it's color or fully change used implementation.

**Comment by UltimateYZ** [comment]
Humm... Well, I took a peek at Styling Introduction it explains many good things, but... I still can't find the solution there. So far, here is the settings which I'm having problems:
![Screenshot from 2020-06-19 11-57-04](https://user-images.githubusercontent.com/55871338/85121312-d9bf9680-b224-11ea-8960-ccd6e645a1d7.png)

And here is the photo showing the title bar customized buttons:
![Screenshot from 2020-06-19 12-10-34](https://user-images.githubusercontent.com/55871338/85121898-f3ada900-b225-11ea-8f7f-306baa6a739d.png)

As you can see the top bar or title bar frame buttons, **Minimize and Resizeable**, are sharing the same settings from id "control" and I only want to set a different colour to each of both components.

**Comment by mgarin** [comment]
Those buttons use styles from [`frame-decorated`](https://github.com/mgarin/weblaf/blob/master/modules/ui/src/com/alee/skin/light/resources/frame.xml#L9) style and `control` style is just a base style for each of the buttons since there is no difference between them in the light and dark skins:
```xml
    <!-- WebLaF-decorated frame -->
    <style type="rootpane" id="frame-decorated" extends="frame">

        <!-- Buttons panel -->
        <style type="panel" id="buttons" extends="grouppane">

            <!-- Custom window decoration control buttons -->
            <style type="button" id="control" padding="3,5,3,5">
                <component>
                    <focusable>false</focusable>
                </component>
                <painter>
                    <decorations>
                        <decoration>
                            <WebShape round="2" />
                            <WebShadow type="outer" width="5" />
                        </decoration>
                    </decorations>
                </painter>
            </style>
            <style type="button" id="minimize" extends="control" />
            <style type="button" id="maximize" extends="control" />
            <style type="button" id="close" extends="control" />

        </style>

    </style>
```
If you want to provide custom style for each specific buttons - simply use the identifiers of the specific button and don't use the `control` one since it applies to all three of them.

**Comment by mgarin** [comment]
Also, just in case, there is a small separate wiki article on window decoration:
https://github.com/mgarin/weblaf/wiki/Window-decoration

**Comment by UltimateYZ** [comment]
Wow! It finally works!

![Screenshot from 2020-06-19 18-39-57](https://user-images.githubusercontent.com/55871338/85159951-76525a80-b25e-11ea-846f-8ee5b9403ea0.png)

Thanks, I really appreciate it!

**Comment by mgarin** [comment]
Glad it helped :)
