### ISSUE TITLE
Any cool layout manager provided by l&f for 'me', fanatic hand code GUI programmer?

### ISSUE THREAD

**Issue by UltimateYZ** [mgarin/weblaf#637]
Hello @mgarin,
Are there any cool layout managers provided by weblaf for manual swing GUI programming? I'm using GridBagLayout, but sometimes it sucks... I tried to use SpringLayout but it's not that flexible like they say... And if the layout manager is apart it would be cool, I would use it with others l&f too! Like FlatLaf, Material, etc...

**Comment by mgarin** [comment]
WebLaF has 50+ custom `LayoutManager`s, but they're mostly used internally for various custom components and some very niche cases, simply to optimize layout performance and avoid piling up additional containers. So I wouldn't call them particularly "cool" or as useful as `GridBagLayout` is for many cases.

If you want to dig into layouts available in WebLaF - you can simply check implementations of `AbstractLayoutManager` class in IDE to see all of them. Except for maybe `TableLayout` which is a 3rd-party layout included in WebLaF sources.

I can maybe name a few layouts that were written specifically for non-internal use:
- `FormLayout` - for aligning components in two columns without excessive use of constraints with some optional constraints
- `HorizontalFlowLayout` - for having a fixed horizontal flow of components with no wrapping
- `VerticalFlowLayout` - for having a fixed vertical flow of components with no wrapping
- `GroupLayout` - for having a fixed horizontal or vertical flow of components with no wrapping and either preferred or fill constraints for each element
- `TableLayout` - the popular static grid layout with settings for each column and row in which you can place components in specific cells or span them across multiple cells on the grid

**Comment by UltimateYZ** [comment]
Wow! Thanks for the tips! Guess, I still have long way to go... These Layout Managers are a bit complex sometimes. My bad habit for getting used to absolute layout is my downfall...

**Comment by mgarin** [comment]
I personally never really liked `GridBagLayout` and always found it excessive for all use cases I've ever had, so I never used it anywhere. Not that it's bad or anything, there is just always a better and more simple layout available for any particular case which would simplify the code and save bits of performance in large applications.

And, well, I do also have a habit of writing new layout managers for various simple use cases where existing simple ones wouldn't help and complex ones would be a complete overkill.
