### ISSUE TITLE
What is "@NotNull" class role exactly?

### ISSUE THREAD

**Issue by UltraBurstXD** [mgarin/weblaf#641]
Hi.
I'm studying those layout managers offered by Oracle for some quite time... They aren't very intuitive or flexible, well maybe except for FlowLayout and GroupLayout (but... it is very verbose...). I've taken interest on your Layout Manager, **FormLayout**. GridBag and Spring Layout I hate 'em, the rest is trash at some point... 

The GridgLayout has some functionalities that GridBagLayout should've inherited, the horizontal gap, hgap and vertical gap, vgap; instead of using insets or others annoying methods to set the gaps manually (Even on Designer it's a big pain...).

I've taken a peek on AbstractLayoutManager, it's very legible and all, but the @NotNull class is giving me some headaches... What does it really do?

**Comment by mgarin** [comment]
You can always check JavaDoc in any particular class if you have WebLaF sources attached to your project, this might help in many cases as I try to keep everything well-documented. Class JavaDoc from [`NotNull`](https://github.com/mgarin/weblaf/blob/master/modules/core/src/com/alee/api/annotations/NotNull.java):
```java
/**
 * An element annotated with {@link NotNull} claims to never return/contain/operate with {@code null} values.
 *
 * @author Mikle Garin
 */
```
It is basically that. Just an annotation that is used to mark methods that cannot return `null` values or method/constructor arguments that cannot have `null` values. It does nothing in runtime and is simply used at IDE level for realtime code validation.

If you aren't familiar with annotations in Java - I recommend reading official document about them:
https://docs.oracle.com/javase/tutorial/java/annotations/

**Comment by UltraBurstXD** [comment]
Thanks, Got it.
