### ISSUE TITLE
change color

### ISSUE THREAD

**Issue by wyj3531** [mgarin/weblaf#675]
there is some proble ?how i can change the Jtable header bg color and for color?
i try to this do this but no effect:
    JTableHeader header = webTable.getTableHeader();
      header.setBackground(Color.black);
      header.setForeground(Color.yellow);
 
and i try to another method and my custom header no effect 
bottom-table  can change but header.why this header i custom no effect.

> `    <style type="tableheader" id="bottom-header">

        <component>
            <opaque>false</opaque>
            <foreground>black</foreground>
        </component>
        <painter>
            <headerHeight>52</headerHeight>
            <topBgColor>255,0,0</topBgColor>
            <bottomBgColor>255,0,0</bottomBgColor>
            <gridColor>170,170,170</gridColor>
        </painter>

        
        <style type="label" id="renderer" extends="shadow" padding="0,2,1,2">
            <component>
                <opaque>true</opaque>
                <horizontalAlignment>0</horizontalAlignment>
            </component>
        </style>

    </style>

    <style type="table" id="bottom-table">
        <component>
            <opaque>true</opaque>
            <background>white</background>
            <foreground>51,51,51</foreground>
            <rowHeight>18</rowHeight>
            <rowMargin>1</rowMargin>
            <fillsViewportHeight>false</fillsViewportHeight>
            <showHorizontalLines>true</showHorizontalLines>
            <showVerticalLines>true</showVerticalLines>
            <gridColor>235,235,237</gridColor>
        </component>
        <painter>
            <decorations>
                <decoration>
                    <BoundsShape />
                    <ColorBackground color="white" />
                </decoration>
            </decorations>

            
            <rowPainter>
                <decorations>
                    <decoration states="odd">
                        <WebShape round="0" />
                        <ColorBackground color="255,255,255" />
                    </decoration>
                </decorations>
            </rowPainter>

            
            <selectionPainter>
                <decorations>
                    <decoration>
                        <WebShape round="0" />
                        <GradientBackground>
                            <color>235, 235, 237</color>
                            <color>235, 235, 237</color>
                        </GradientBackground>
                    </decoration>
                </decorations>
            </selectionPainter>

        </painter>

        
        <style type="tableheader" id="bottom-header" />

    </style>`

**Comment by wyj3531** [comment]
DefaultTableModel defaultTableModel = new DefaultTableModel(data, columnNames);
        WebTable table = new WebTable(StyleId.of("bottom-table"), defaultTableModel);
        table.setRowHeight(30);
        JTableHeader tableHeader = table.getTableHeader();
        /*tableHeader.setOpaque(true);
        tableHeader.setBackground(new Color(255,0,0));*/
        tableHeader.setPreferredSize(new Dimension(1,30));
        JScrollPane scrollPane = new JScrollPane(table, ScrollPaneConstants.VERTICAL_SCROLLBAR_AS_NEEDED, 
        ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scrollPane.putClientProperty(StyleId.STYLE_PROPERTY, StyleId.scrollpaneTransparentButtonless);

**Comment by mgarin** [comment]
There are two ways in which you can customize table header style -

1. Modify default table header style - this will modify header style for all tables. Table header is not yet fully customizable since it uses a specific `TableHeaderPainter` painter, but you can still adjust colors it uses. Here is the default [`tableheader.xml`](https://github.com/mgarin/weblaf/blob/master/modules/ui/src/com/alee/skin/light/resources/tableheader.xml) contents you can override:
```xml
<skin xmlns="http://weblookandfeel.com/XmlSkin">

    <!-- Table header -->
    <style type="tableheader">
        <component>
            <opaque>true</opaque>
            <foreground>black</foreground>
        </component>
        <painter>
            <headerHeight>22</headerHeight>
            <topBgColor>226,226,226</topBgColor>
            <bottomBgColor>201,201,201</bottomBgColor>
            <gridColor>170,170,170</gridColor>
        </painter>

        <!-- Default table header cell renderer label -->
        <style type="label" id="renderer" extends="shadow" padding="0,2,1,2">
            <component>
                <opaque>true</opaque>
                <horizontalAlignment>0</horizontalAlignment>
            </component>
        </style>

    </style>

</skin>
```

2. Modify default table style or create a custom one. In that table style you can customize header style directly. Default table style reuses the header style from [`tableheader.xml`](https://github.com/mgarin/weblaf/blob/master/modules/ui/src/com/alee/skin/light/resources/tableheader.xml), but nothing stops you from adjusting it:
```xml
    <!-- Table -->
    <style type="table" id="custom">
    
        <!-- Table header -->
        <style type="tableheader" id="header">
                <!-- Custom settings -->
        </style>

    </style>
```

First option will allow you to adjust all headers for all tables at once, second option will allow you to customize header only for the tables your table style will be applied to.

**Comment by wyj3531** [comment]
en. fixed it  by  option 2. thank you
