### ISSUE TITLE
WebTable how to merge head row?

### ISSUE THREAD

**Issue by wyj3531** [mgarin/weblaf#679]
WebTable how to merge head row1 and row2 with a new row?

**Comment by mgarin** [comment]
If you mean something like this -

![image](https://user-images.githubusercontent.com/2361389/139833223-561d536d-3906-4673-98c4-fe116d384260.png)

It isn't supported yet in WebLaF and not available in standard Swing either.

There are some examples out there, like this one:
http://www.java2s.com/Code/Java/Swing-Components/GroupableGroupHeaderExample.htm
But I'm not sure whether it will work or how well it will work.

**Comment by mgarin** [comment]
I've added a separate feature for future addition: #680

But it's most probably not coming anytime soon, so if you need an immediate solution - your best shot is trying to implement one yourself and then replace it later with WebLaF one, once it becomes available.

**Comment by mgarin** [comment]
Will be closing this issue
All groupable table header -related discussions will be held in #680
