### ISSUE TITLE
jTextPane about alignment

### ISSUE THREAD

**Issue by wyj3531** [mgarin/weblaf#681]
![0EC41E4A-A9FB-47cc-BEF4-9308BF3A1711](https://user-images.githubusercontent.com/23471836/142600812-992dde90-2bf8-4039-b6a9-2bf23aed48d2.png)

just like pic ,i use jTextPane  add the button(data1), and input the text( testest).and how i make the both in center vertical .
i custom a boxview can make the button in center vertical . but the input text  how to do ?

**Comment by mgarin** [comment]
What you're probably looking for is aligning components by their baseline.

I recommend reading this official article on Swing's `GroupLayout` -
https://docs.oracle.com/javase/tutorial/uiswing/layout/groupExample.html
Specifically "Vertical layout" section that has some examples.

I'm personally not completely sure whether `JTextPane` supports baseline alignment or not, but considering that `JTextArea` does - I don't see why `JTextPane` wouldn't.
