### ISSUE TITLE
The scroll bar is not drawn,How do I set him up?

### ISSUE THREAD

**Issue by xcfdszzr** [mgarin/weblaf#683]
final JScrollPane scrollPane = new JScrollPane ();
            scrollPane.putClientProperty ( StyleId.STYLE_PROPERTY,  StyleId.scrollpaneTransparentHovering );
            scrollPane.setPreferredSize ( new Dimension ( 200, 160 ) );
            WebPanel webPanel = new WebPanel(new LineLayout(LineLayout.VERTICAL));
            for (int i = 0; i < 100; i++) {
                webPanel.add(new WebLabel("11111"));
            }
            scrollPane.setViewportView(webPanel);
           
![image](https://user-images.githubusercontent.com/10494040/143794319-287b9c87-bfe1-4942-916c-77055c40d16f.png)

When I add a component, the scrollbar becomes undrawable or the drawing is dirty

**Comment by mgarin** [comment]
This happens because the `WebPanel` you add into scroll pane is opaque. If you want any component to hover over other one without visual glitches like on your screenshot - that other component needs to be non-opaque, otherwise repaint calls will not make it past that other component when necessary.

**Comment by xcfdszzr** [comment]
> This happens because the `WebPanel` you add into scroll pane is opaque. If you want any component to hover over other one without visual glitches like on your screenshot - that other component needs to be non-opaque, otherwise repaint calls will not make it past that other component when necessary.

Thank you author, my problem has been solved
