### ISSUE TITLE
Possibility to hide single tab in WebTabbedPane

### ISSUE THREAD

**Issue by Endogen** [mgarin/weblaf#74]
Currently there is no way to hide the tab bar if only one tab is present. But i think that this would be a pretty cool (optional) feature!

It is possible to call

```
webTabbedPane.getTabComponentAt(0).setVisible(false);
```

but that will hide everything, not just the tab bar. Also see this for further information: http://stackoverflow.com/questions/942500/is-there-a-way-to-hide-the-tab-bar-of-jtabbedpane-if-only-one-tab-exists

**Comment by mgarin** [comment]
This is something that is now easily doable due to `JTabbedPane` UI rework.
I will quickly add this in v1.2.11

**Comment by mgarin** [comment]
This is now implemented in `WebTabbedPane`:
```java
    /**
     * Returns whether or not tab area should be hidden when only one tab is opened.
     *
     * @return {@code true} if tab area should be hidden when only one tab is opened, {@code false} otherwise
     */
    public boolean isHideSingleTab ()

    /**
     * Sets whether or not tab area should be hidden when only one tab is opened.
     *
     * @param hide whether or not tab area should be hidden when only one tab is opened
     */
    public void setHideSingleTab ( final boolean hide )
```

It can also be used for `JTabbedPane` through new property utilities:
```java
final JTabbedPane tabbedPane = new JTabbedPane ();

// Hiding single tabs for JTabbedPane
WebTabbedPane.HIDE_SINGLE_TAB_PROPERTY.set ( tabbedPane, true );

// Checking property value for JTabbedPane
final boolean hide = WebTabbedPane.HIDE_SINGLE_TAB_PROPERTY.get ( tabbedPane );
```
